#pragma once
// MESSAGE TRITRI_TARGET PACKING

#include <stdint.h>

#define MAVLINK_MSG_ID_TRITRI_TARGET 53901


typedef struct __mavlink_tritri_target_t {
 uint64_t time_usec; /*< [us] Timestamp (UNIX epoch, microseconds UTC).*/
 uint64_t target_time_usec; /*< [us] Timestamp when the target fix was valid (UNIX epoch, microseconds UTC).*/
 uint32_t target_id; /*<  Unique target identifier generated by the source system.*/
 uint32_t target_set_id; /*<  Parent target set identifier. 0 = none.*/
 uint32_t flags; /*<  Target warning and status flags.*/
 int32_t lat; /*< [degE7] Target latitude, WGS84. INT32_MAX if unknown.*/
 int32_t lon; /*< [degE7] Target longitude, WGS84. INT32_MAX if unknown.*/
 float alt; /*< [m] Target altitude, MSL. NaN if unknown.*/
 float vx; /*< [m/s] Velocity north (NED). NaN if unknown.*/
 float vy; /*< [m/s] Velocity east (NED). NaN if unknown.*/
 float vz; /*< [m/s] Velocity down (NED). NaN if unknown.*/
 float cov_pos_x; /*<  Position covariance, north axis (m^2). NaN if unknown.*/
 float cov_pos_y; /*<  Position covariance, east axis (m^2). NaN if unknown.*/
 float cov_pos_z; /*<  Position covariance, down axis (m^2). NaN if unknown.*/
 float cov_vel_x; /*<  Velocity covariance, north axis (m^2/s^2). NaN if unknown.*/
 float cov_vel_y; /*<  Velocity covariance, east axis (m^2/s^2). NaN if unknown.*/
 float cov_vel_z; /*<  Velocity covariance, down axis (m^2/s^2). NaN if unknown.*/
 uint16_t confidence; /*<  Classification or detection confidence scaled 0-10000.*/
 uint8_t track_uid[16]; /*<  Track UID correlating to TRITRI_TRACK. All-zero if unknown.*/
 char target_name[16]; /*<  Short human-readable callsign (null-terminated).*/
 uint8_t target_class; /*<  Target classification.*/
 uint8_t target_domain; /*<  Primary operating domain.*/
 uint8_t target_force; /*<  Force affiliation.*/
 uint8_t sensor_type; /*<  Primary sensor source.*/
 uint8_t tle_category; /*<  Target-location-error category label. 0 if unset.*/
 uint8_t restricted_target_flags; /*<  No-strike / restricted / NFA flags. 0 if none.*/
} mavlink_tritri_target_t;

#define MAVLINK_MSG_ID_TRITRI_TARGET_LEN 116
#define MAVLINK_MSG_ID_TRITRI_TARGET_MIN_LEN 116
#define MAVLINK_MSG_ID_53901_LEN 116
#define MAVLINK_MSG_ID_53901_MIN_LEN 116

#define MAVLINK_MSG_ID_TRITRI_TARGET_CRC 67
#define MAVLINK_MSG_ID_53901_CRC 67

#define MAVLINK_MSG_TRITRI_TARGET_FIELD_TRACK_UID_LEN 16
#define MAVLINK_MSG_TRITRI_TARGET_FIELD_TARGET_NAME_LEN 16

#if MAVLINK_COMMAND_24BIT
#define MAVLINK_MESSAGE_INFO_TRITRI_TARGET { \
    53901, \
    "TRITRI_TARGET", \
    26, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_tritri_target_t, time_usec) }, \
         { "target_time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 8, offsetof(mavlink_tritri_target_t, target_time_usec) }, \
         { "track_uid", NULL, MAVLINK_TYPE_UINT8_T, 16, 78, offsetof(mavlink_tritri_target_t, track_uid) }, \
         { "target_name", NULL, MAVLINK_TYPE_CHAR, 16, 94, offsetof(mavlink_tritri_target_t, target_name) }, \
         { "target_id", NULL, MAVLINK_TYPE_UINT32_T, 0, 16, offsetof(mavlink_tritri_target_t, target_id) }, \
         { "target_set_id", NULL, MAVLINK_TYPE_UINT32_T, 0, 20, offsetof(mavlink_tritri_target_t, target_set_id) }, \
         { "flags", NULL, MAVLINK_TYPE_UINT32_T, 0, 24, offsetof(mavlink_tritri_target_t, flags) }, \
         { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 28, offsetof(mavlink_tritri_target_t, lat) }, \
         { "lon", NULL, MAVLINK_TYPE_INT32_T, 0, 32, offsetof(mavlink_tritri_target_t, lon) }, \
         { "alt", NULL, MAVLINK_TYPE_FLOAT, 0, 36, offsetof(mavlink_tritri_target_t, alt) }, \
         { "vx", NULL, MAVLINK_TYPE_FLOAT, 0, 40, offsetof(mavlink_tritri_target_t, vx) }, \
         { "vy", NULL, MAVLINK_TYPE_FLOAT, 0, 44, offsetof(mavlink_tritri_target_t, vy) }, \
         { "vz", NULL, MAVLINK_TYPE_FLOAT, 0, 48, offsetof(mavlink_tritri_target_t, vz) }, \
         { "cov_pos_x", NULL, MAVLINK_TYPE_FLOAT, 0, 52, offsetof(mavlink_tritri_target_t, cov_pos_x) }, \
         { "cov_pos_y", NULL, MAVLINK_TYPE_FLOAT, 0, 56, offsetof(mavlink_tritri_target_t, cov_pos_y) }, \
         { "cov_pos_z", NULL, MAVLINK_TYPE_FLOAT, 0, 60, offsetof(mavlink_tritri_target_t, cov_pos_z) }, \
         { "cov_vel_x", NULL, MAVLINK_TYPE_FLOAT, 0, 64, offsetof(mavlink_tritri_target_t, cov_vel_x) }, \
         { "cov_vel_y", NULL, MAVLINK_TYPE_FLOAT, 0, 68, offsetof(mavlink_tritri_target_t, cov_vel_y) }, \
         { "cov_vel_z", NULL, MAVLINK_TYPE_FLOAT, 0, 72, offsetof(mavlink_tritri_target_t, cov_vel_z) }, \
         { "confidence", NULL, MAVLINK_TYPE_UINT16_T, 0, 76, offsetof(mavlink_tritri_target_t, confidence) }, \
         { "target_class", NULL, MAVLINK_TYPE_UINT8_T, 0, 110, offsetof(mavlink_tritri_target_t, target_class) }, \
         { "target_domain", NULL, MAVLINK_TYPE_UINT8_T, 0, 111, offsetof(mavlink_tritri_target_t, target_domain) }, \
         { "target_force", NULL, MAVLINK_TYPE_UINT8_T, 0, 112, offsetof(mavlink_tritri_target_t, target_force) }, \
         { "sensor_type", NULL, MAVLINK_TYPE_UINT8_T, 0, 113, offsetof(mavlink_tritri_target_t, sensor_type) }, \
         { "tle_category", NULL, MAVLINK_TYPE_UINT8_T, 0, 114, offsetof(mavlink_tritri_target_t, tle_category) }, \
         { "restricted_target_flags", NULL, MAVLINK_TYPE_UINT8_T, 0, 115, offsetof(mavlink_tritri_target_t, restricted_target_flags) }, \
         } \
}
#else
#define MAVLINK_MESSAGE_INFO_TRITRI_TARGET { \
    "TRITRI_TARGET", \
    26, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_tritri_target_t, time_usec) }, \
         { "target_time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 8, offsetof(mavlink_tritri_target_t, target_time_usec) }, \
         { "track_uid", NULL, MAVLINK_TYPE_UINT8_T, 16, 78, offsetof(mavlink_tritri_target_t, track_uid) }, \
         { "target_name", NULL, MAVLINK_TYPE_CHAR, 16, 94, offsetof(mavlink_tritri_target_t, target_name) }, \
         { "target_id", NULL, MAVLINK_TYPE_UINT32_T, 0, 16, offsetof(mavlink_tritri_target_t, target_id) }, \
         { "target_set_id", NULL, MAVLINK_TYPE_UINT32_T, 0, 20, offsetof(mavlink_tritri_target_t, target_set_id) }, \
         { "flags", NULL, MAVLINK_TYPE_UINT32_T, 0, 24, offsetof(mavlink_tritri_target_t, flags) }, \
         { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 28, offsetof(mavlink_tritri_target_t, lat) }, \
         { "lon", NULL, MAVLINK_TYPE_INT32_T, 0, 32, offsetof(mavlink_tritri_target_t, lon) }, \
         { "alt", NULL, MAVLINK_TYPE_FLOAT, 0, 36, offsetof(mavlink_tritri_target_t, alt) }, \
         { "vx", NULL, MAVLINK_TYPE_FLOAT, 0, 40, offsetof(mavlink_tritri_target_t, vx) }, \
         { "vy", NULL, MAVLINK_TYPE_FLOAT, 0, 44, offsetof(mavlink_tritri_target_t, vy) }, \
         { "vz", NULL, MAVLINK_TYPE_FLOAT, 0, 48, offsetof(mavlink_tritri_target_t, vz) }, \
         { "cov_pos_x", NULL, MAVLINK_TYPE_FLOAT, 0, 52, offsetof(mavlink_tritri_target_t, cov_pos_x) }, \
         { "cov_pos_y", NULL, MAVLINK_TYPE_FLOAT, 0, 56, offsetof(mavlink_tritri_target_t, cov_pos_y) }, \
         { "cov_pos_z", NULL, MAVLINK_TYPE_FLOAT, 0, 60, offsetof(mavlink_tritri_target_t, cov_pos_z) }, \
         { "cov_vel_x", NULL, MAVLINK_TYPE_FLOAT, 0, 64, offsetof(mavlink_tritri_target_t, cov_vel_x) }, \
         { "cov_vel_y", NULL, MAVLINK_TYPE_FLOAT, 0, 68, offsetof(mavlink_tritri_target_t, cov_vel_y) }, \
         { "cov_vel_z", NULL, MAVLINK_TYPE_FLOAT, 0, 72, offsetof(mavlink_tritri_target_t, cov_vel_z) }, \
         { "confidence", NULL, MAVLINK_TYPE_UINT16_T, 0, 76, offsetof(mavlink_tritri_target_t, confidence) }, \
         { "target_class", NULL, MAVLINK_TYPE_UINT8_T, 0, 110, offsetof(mavlink_tritri_target_t, target_class) }, \
         { "target_domain", NULL, MAVLINK_TYPE_UINT8_T, 0, 111, offsetof(mavlink_tritri_target_t, target_domain) }, \
         { "target_force", NULL, MAVLINK_TYPE_UINT8_T, 0, 112, offsetof(mavlink_tritri_target_t, target_force) }, \
         { "sensor_type", NULL, MAVLINK_TYPE_UINT8_T, 0, 113, offsetof(mavlink_tritri_target_t, sensor_type) }, \
         { "tle_category", NULL, MAVLINK_TYPE_UINT8_T, 0, 114, offsetof(mavlink_tritri_target_t, tle_category) }, \
         { "restricted_target_flags", NULL, MAVLINK_TYPE_UINT8_T, 0, 115, offsetof(mavlink_tritri_target_t, restricted_target_flags) }, \
         } \
}
#endif

/**
 * @brief Pack a tritri_target message
 * @param system_id ID of this system
 * @param component_id ID of this component (e.g. 200 for IMU)
 * @param msg The MAVLink message to compress the data into
 *
 * @param time_usec [us] Timestamp (UNIX epoch, microseconds UTC).
 * @param target_time_usec [us] Timestamp when the target fix was valid (UNIX epoch, microseconds UTC).
 * @param track_uid  Track UID correlating to TRITRI_TRACK. All-zero if unknown.
 * @param target_name  Short human-readable callsign (null-terminated).
 * @param target_id  Unique target identifier generated by the source system.
 * @param target_set_id  Parent target set identifier. 0 = none.
 * @param flags  Target warning and status flags.
 * @param lat [degE7] Target latitude, WGS84. INT32_MAX if unknown.
 * @param lon [degE7] Target longitude, WGS84. INT32_MAX if unknown.
 * @param alt [m] Target altitude, MSL. NaN if unknown.
 * @param vx [m/s] Velocity north (NED). NaN if unknown.
 * @param vy [m/s] Velocity east (NED). NaN if unknown.
 * @param vz [m/s] Velocity down (NED). NaN if unknown.
 * @param cov_pos_x  Position covariance, north axis (m^2). NaN if unknown.
 * @param cov_pos_y  Position covariance, east axis (m^2). NaN if unknown.
 * @param cov_pos_z  Position covariance, down axis (m^2). NaN if unknown.
 * @param cov_vel_x  Velocity covariance, north axis (m^2/s^2). NaN if unknown.
 * @param cov_vel_y  Velocity covariance, east axis (m^2/s^2). NaN if unknown.
 * @param cov_vel_z  Velocity covariance, down axis (m^2/s^2). NaN if unknown.
 * @param confidence  Classification or detection confidence scaled 0-10000.
 * @param target_class  Target classification.
 * @param target_domain  Primary operating domain.
 * @param target_force  Force affiliation.
 * @param sensor_type  Primary sensor source.
 * @param tle_category  Target-location-error category label. 0 if unset.
 * @param restricted_target_flags  No-strike / restricted / NFA flags. 0 if none.
 * @return length of the message in bytes (excluding serial stream start sign)
 */
static inline uint16_t mavlink_msg_tritri_target_pack(uint32_t system_id, uint8_t component_id, mavlink_message_t* msg,
                               uint64_t time_usec, uint64_t target_time_usec, const uint8_t *track_uid, const char *target_name, uint32_t target_id, uint32_t target_set_id, uint32_t flags, int32_t lat, int32_t lon, float alt, float vx, float vy, float vz, float cov_pos_x, float cov_pos_y, float cov_pos_z, float cov_vel_x, float cov_vel_y, float cov_vel_z, uint16_t confidence, uint8_t target_class, uint8_t target_domain, uint8_t target_force, uint8_t sensor_type, uint8_t tle_category, uint8_t restricted_target_flags)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    char buf[MAVLINK_MSG_ID_TRITRI_TARGET_LEN];
    _mav_put_uint64_t(buf, 0, time_usec);
    _mav_put_uint64_t(buf, 8, target_time_usec);
    _mav_put_uint32_t(buf, 16, target_id);
    _mav_put_uint32_t(buf, 20, target_set_id);
    _mav_put_uint32_t(buf, 24, flags);
    _mav_put_int32_t(buf, 28, lat);
    _mav_put_int32_t(buf, 32, lon);
    _mav_put_float(buf, 36, alt);
    _mav_put_float(buf, 40, vx);
    _mav_put_float(buf, 44, vy);
    _mav_put_float(buf, 48, vz);
    _mav_put_float(buf, 52, cov_pos_x);
    _mav_put_float(buf, 56, cov_pos_y);
    _mav_put_float(buf, 60, cov_pos_z);
    _mav_put_float(buf, 64, cov_vel_x);
    _mav_put_float(buf, 68, cov_vel_y);
    _mav_put_float(buf, 72, cov_vel_z);
    _mav_put_uint16_t(buf, 76, confidence);
    _mav_put_uint8_t(buf, 110, target_class);
    _mav_put_uint8_t(buf, 111, target_domain);
    _mav_put_uint8_t(buf, 112, target_force);
    _mav_put_uint8_t(buf, 113, sensor_type);
    _mav_put_uint8_t(buf, 114, tle_category);
    _mav_put_uint8_t(buf, 115, restricted_target_flags);
    _mav_put_uint8_t_array(buf, 78, track_uid, 16);
    _mav_put_char_array(buf, 94, target_name, 16);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), buf, MAVLINK_MSG_ID_TRITRI_TARGET_LEN);
#else
    mavlink_tritri_target_t packet;
    packet.time_usec = time_usec;
    packet.target_time_usec = target_time_usec;
    packet.target_id = target_id;
    packet.target_set_id = target_set_id;
    packet.flags = flags;
    packet.lat = lat;
    packet.lon = lon;
    packet.alt = alt;
    packet.vx = vx;
    packet.vy = vy;
    packet.vz = vz;
    packet.cov_pos_x = cov_pos_x;
    packet.cov_pos_y = cov_pos_y;
    packet.cov_pos_z = cov_pos_z;
    packet.cov_vel_x = cov_vel_x;
    packet.cov_vel_y = cov_vel_y;
    packet.cov_vel_z = cov_vel_z;
    packet.confidence = confidence;
    packet.target_class = target_class;
    packet.target_domain = target_domain;
    packet.target_force = target_force;
    packet.sensor_type = sensor_type;
    packet.tle_category = tle_category;
    packet.restricted_target_flags = restricted_target_flags;
    mav_array_memcpy(packet.track_uid, track_uid, sizeof(uint8_t)*16);
    mav_array_memcpy(packet.target_name, target_name, sizeof(char)*16);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), &packet, MAVLINK_MSG_ID_TRITRI_TARGET_LEN);
#endif

    msg->msgid = MAVLINK_MSG_ID_TRITRI_TARGET;
    return mavlink_finalize_message(msg, system_id, component_id, MAVLINK_MSG_ID_TRITRI_TARGET_MIN_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_CRC);
}

/**
 * @brief Pack a tritri_target message
 * @param system_id ID of this system
 * @param component_id ID of this component (e.g. 200 for IMU)
 * @param status MAVLink status structure
 * @param msg The MAVLink message to compress the data into
 *
 * @param time_usec [us] Timestamp (UNIX epoch, microseconds UTC).
 * @param target_time_usec [us] Timestamp when the target fix was valid (UNIX epoch, microseconds UTC).
 * @param track_uid  Track UID correlating to TRITRI_TRACK. All-zero if unknown.
 * @param target_name  Short human-readable callsign (null-terminated).
 * @param target_id  Unique target identifier generated by the source system.
 * @param target_set_id  Parent target set identifier. 0 = none.
 * @param flags  Target warning and status flags.
 * @param lat [degE7] Target latitude, WGS84. INT32_MAX if unknown.
 * @param lon [degE7] Target longitude, WGS84. INT32_MAX if unknown.
 * @param alt [m] Target altitude, MSL. NaN if unknown.
 * @param vx [m/s] Velocity north (NED). NaN if unknown.
 * @param vy [m/s] Velocity east (NED). NaN if unknown.
 * @param vz [m/s] Velocity down (NED). NaN if unknown.
 * @param cov_pos_x  Position covariance, north axis (m^2). NaN if unknown.
 * @param cov_pos_y  Position covariance, east axis (m^2). NaN if unknown.
 * @param cov_pos_z  Position covariance, down axis (m^2). NaN if unknown.
 * @param cov_vel_x  Velocity covariance, north axis (m^2/s^2). NaN if unknown.
 * @param cov_vel_y  Velocity covariance, east axis (m^2/s^2). NaN if unknown.
 * @param cov_vel_z  Velocity covariance, down axis (m^2/s^2). NaN if unknown.
 * @param confidence  Classification or detection confidence scaled 0-10000.
 * @param target_class  Target classification.
 * @param target_domain  Primary operating domain.
 * @param target_force  Force affiliation.
 * @param sensor_type  Primary sensor source.
 * @param tle_category  Target-location-error category label. 0 if unset.
 * @param restricted_target_flags  No-strike / restricted / NFA flags. 0 if none.
 * @return length of the message in bytes (excluding serial stream start sign)
 */
static inline uint16_t mavlink_msg_tritri_target_pack_status(uint32_t system_id, uint8_t component_id, mavlink_status_t *_status, mavlink_message_t* msg,
                               uint64_t time_usec, uint64_t target_time_usec, const uint8_t *track_uid, const char *target_name, uint32_t target_id, uint32_t target_set_id, uint32_t flags, int32_t lat, int32_t lon, float alt, float vx, float vy, float vz, float cov_pos_x, float cov_pos_y, float cov_pos_z, float cov_vel_x, float cov_vel_y, float cov_vel_z, uint16_t confidence, uint8_t target_class, uint8_t target_domain, uint8_t target_force, uint8_t sensor_type, uint8_t tle_category, uint8_t restricted_target_flags)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    char buf[MAVLINK_MSG_ID_TRITRI_TARGET_LEN];
    _mav_put_uint64_t(buf, 0, time_usec);
    _mav_put_uint64_t(buf, 8, target_time_usec);
    _mav_put_uint32_t(buf, 16, target_id);
    _mav_put_uint32_t(buf, 20, target_set_id);
    _mav_put_uint32_t(buf, 24, flags);
    _mav_put_int32_t(buf, 28, lat);
    _mav_put_int32_t(buf, 32, lon);
    _mav_put_float(buf, 36, alt);
    _mav_put_float(buf, 40, vx);
    _mav_put_float(buf, 44, vy);
    _mav_put_float(buf, 48, vz);
    _mav_put_float(buf, 52, cov_pos_x);
    _mav_put_float(buf, 56, cov_pos_y);
    _mav_put_float(buf, 60, cov_pos_z);
    _mav_put_float(buf, 64, cov_vel_x);
    _mav_put_float(buf, 68, cov_vel_y);
    _mav_put_float(buf, 72, cov_vel_z);
    _mav_put_uint16_t(buf, 76, confidence);
    _mav_put_uint8_t(buf, 110, target_class);
    _mav_put_uint8_t(buf, 111, target_domain);
    _mav_put_uint8_t(buf, 112, target_force);
    _mav_put_uint8_t(buf, 113, sensor_type);
    _mav_put_uint8_t(buf, 114, tle_category);
    _mav_put_uint8_t(buf, 115, restricted_target_flags);
    _mav_put_uint8_t_array(buf, 78, track_uid, 16);
    _mav_put_char_array(buf, 94, target_name, 16);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), buf, MAVLINK_MSG_ID_TRITRI_TARGET_LEN);
#else
    mavlink_tritri_target_t packet;
    packet.time_usec = time_usec;
    packet.target_time_usec = target_time_usec;
    packet.target_id = target_id;
    packet.target_set_id = target_set_id;
    packet.flags = flags;
    packet.lat = lat;
    packet.lon = lon;
    packet.alt = alt;
    packet.vx = vx;
    packet.vy = vy;
    packet.vz = vz;
    packet.cov_pos_x = cov_pos_x;
    packet.cov_pos_y = cov_pos_y;
    packet.cov_pos_z = cov_pos_z;
    packet.cov_vel_x = cov_vel_x;
    packet.cov_vel_y = cov_vel_y;
    packet.cov_vel_z = cov_vel_z;
    packet.confidence = confidence;
    packet.target_class = target_class;
    packet.target_domain = target_domain;
    packet.target_force = target_force;
    packet.sensor_type = sensor_type;
    packet.tle_category = tle_category;
    packet.restricted_target_flags = restricted_target_flags;
    mav_array_memcpy(packet.track_uid, track_uid, sizeof(uint8_t)*16);
    mav_array_memcpy(packet.target_name, target_name, sizeof(char)*16);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), &packet, MAVLINK_MSG_ID_TRITRI_TARGET_LEN);
#endif

    msg->msgid = MAVLINK_MSG_ID_TRITRI_TARGET;
#if MAVLINK_CRC_EXTRA
    return mavlink_finalize_message_buffer(msg, system_id, component_id, _status, MAVLINK_MSG_ID_TRITRI_TARGET_MIN_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_CRC);
#else
    return mavlink_finalize_message_buffer(msg, system_id, component_id, _status, MAVLINK_MSG_ID_TRITRI_TARGET_MIN_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_LEN, 0);
#endif
}

/**
 * @brief Pack a tritri_target message on a channel
 * @param system_id ID of this system
 * @param component_id ID of this component (e.g. 200 for IMU)
 * @param chan The MAVLink channel this message will be sent over
 * @param msg The MAVLink message to compress the data into
 * @param time_usec [us] Timestamp (UNIX epoch, microseconds UTC).
 * @param target_time_usec [us] Timestamp when the target fix was valid (UNIX epoch, microseconds UTC).
 * @param track_uid  Track UID correlating to TRITRI_TRACK. All-zero if unknown.
 * @param target_name  Short human-readable callsign (null-terminated).
 * @param target_id  Unique target identifier generated by the source system.
 * @param target_set_id  Parent target set identifier. 0 = none.
 * @param flags  Target warning and status flags.
 * @param lat [degE7] Target latitude, WGS84. INT32_MAX if unknown.
 * @param lon [degE7] Target longitude, WGS84. INT32_MAX if unknown.
 * @param alt [m] Target altitude, MSL. NaN if unknown.
 * @param vx [m/s] Velocity north (NED). NaN if unknown.
 * @param vy [m/s] Velocity east (NED). NaN if unknown.
 * @param vz [m/s] Velocity down (NED). NaN if unknown.
 * @param cov_pos_x  Position covariance, north axis (m^2). NaN if unknown.
 * @param cov_pos_y  Position covariance, east axis (m^2). NaN if unknown.
 * @param cov_pos_z  Position covariance, down axis (m^2). NaN if unknown.
 * @param cov_vel_x  Velocity covariance, north axis (m^2/s^2). NaN if unknown.
 * @param cov_vel_y  Velocity covariance, east axis (m^2/s^2). NaN if unknown.
 * @param cov_vel_z  Velocity covariance, down axis (m^2/s^2). NaN if unknown.
 * @param confidence  Classification or detection confidence scaled 0-10000.
 * @param target_class  Target classification.
 * @param target_domain  Primary operating domain.
 * @param target_force  Force affiliation.
 * @param sensor_type  Primary sensor source.
 * @param tle_category  Target-location-error category label. 0 if unset.
 * @param restricted_target_flags  No-strike / restricted / NFA flags. 0 if none.
 * @return length of the message in bytes (excluding serial stream start sign)
 */
static inline uint16_t mavlink_msg_tritri_target_pack_chan(uint32_t system_id, uint8_t component_id, uint8_t chan,
                               mavlink_message_t* msg,
                                   uint64_t time_usec,uint64_t target_time_usec,const uint8_t *track_uid,const char *target_name,uint32_t target_id,uint32_t target_set_id,uint32_t flags,int32_t lat,int32_t lon,float alt,float vx,float vy,float vz,float cov_pos_x,float cov_pos_y,float cov_pos_z,float cov_vel_x,float cov_vel_y,float cov_vel_z,uint16_t confidence,uint8_t target_class,uint8_t target_domain,uint8_t target_force,uint8_t sensor_type,uint8_t tle_category,uint8_t restricted_target_flags)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    char buf[MAVLINK_MSG_ID_TRITRI_TARGET_LEN];
    _mav_put_uint64_t(buf, 0, time_usec);
    _mav_put_uint64_t(buf, 8, target_time_usec);
    _mav_put_uint32_t(buf, 16, target_id);
    _mav_put_uint32_t(buf, 20, target_set_id);
    _mav_put_uint32_t(buf, 24, flags);
    _mav_put_int32_t(buf, 28, lat);
    _mav_put_int32_t(buf, 32, lon);
    _mav_put_float(buf, 36, alt);
    _mav_put_float(buf, 40, vx);
    _mav_put_float(buf, 44, vy);
    _mav_put_float(buf, 48, vz);
    _mav_put_float(buf, 52, cov_pos_x);
    _mav_put_float(buf, 56, cov_pos_y);
    _mav_put_float(buf, 60, cov_pos_z);
    _mav_put_float(buf, 64, cov_vel_x);
    _mav_put_float(buf, 68, cov_vel_y);
    _mav_put_float(buf, 72, cov_vel_z);
    _mav_put_uint16_t(buf, 76, confidence);
    _mav_put_uint8_t(buf, 110, target_class);
    _mav_put_uint8_t(buf, 111, target_domain);
    _mav_put_uint8_t(buf, 112, target_force);
    _mav_put_uint8_t(buf, 113, sensor_type);
    _mav_put_uint8_t(buf, 114, tle_category);
    _mav_put_uint8_t(buf, 115, restricted_target_flags);
    _mav_put_uint8_t_array(buf, 78, track_uid, 16);
    _mav_put_char_array(buf, 94, target_name, 16);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), buf, MAVLINK_MSG_ID_TRITRI_TARGET_LEN);
#else
    mavlink_tritri_target_t packet;
    packet.time_usec = time_usec;
    packet.target_time_usec = target_time_usec;
    packet.target_id = target_id;
    packet.target_set_id = target_set_id;
    packet.flags = flags;
    packet.lat = lat;
    packet.lon = lon;
    packet.alt = alt;
    packet.vx = vx;
    packet.vy = vy;
    packet.vz = vz;
    packet.cov_pos_x = cov_pos_x;
    packet.cov_pos_y = cov_pos_y;
    packet.cov_pos_z = cov_pos_z;
    packet.cov_vel_x = cov_vel_x;
    packet.cov_vel_y = cov_vel_y;
    packet.cov_vel_z = cov_vel_z;
    packet.confidence = confidence;
    packet.target_class = target_class;
    packet.target_domain = target_domain;
    packet.target_force = target_force;
    packet.sensor_type = sensor_type;
    packet.tle_category = tle_category;
    packet.restricted_target_flags = restricted_target_flags;
    mav_array_memcpy(packet.track_uid, track_uid, sizeof(uint8_t)*16);
    mav_array_memcpy(packet.target_name, target_name, sizeof(char)*16);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), &packet, MAVLINK_MSG_ID_TRITRI_TARGET_LEN);
#endif

    msg->msgid = MAVLINK_MSG_ID_TRITRI_TARGET;
    return mavlink_finalize_message_chan(msg, system_id, component_id, chan, MAVLINK_MSG_ID_TRITRI_TARGET_MIN_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_CRC);
}

/**
 * @brief Encode a tritri_target struct
 *
 * @param system_id ID of this system
 * @param component_id ID of this component (e.g. 200 for IMU)
 * @param msg The MAVLink message to compress the data into
 * @param tritri_target C-struct to read the message contents from
 */
static inline uint16_t mavlink_msg_tritri_target_encode(uint32_t system_id, uint8_t component_id, mavlink_message_t* msg, const mavlink_tritri_target_t* tritri_target)
{
    return mavlink_msg_tritri_target_pack(system_id, component_id, msg, tritri_target->time_usec, tritri_target->target_time_usec, tritri_target->track_uid, tritri_target->target_name, tritri_target->target_id, tritri_target->target_set_id, tritri_target->flags, tritri_target->lat, tritri_target->lon, tritri_target->alt, tritri_target->vx, tritri_target->vy, tritri_target->vz, tritri_target->cov_pos_x, tritri_target->cov_pos_y, tritri_target->cov_pos_z, tritri_target->cov_vel_x, tritri_target->cov_vel_y, tritri_target->cov_vel_z, tritri_target->confidence, tritri_target->target_class, tritri_target->target_domain, tritri_target->target_force, tritri_target->sensor_type, tritri_target->tle_category, tritri_target->restricted_target_flags);
}

/**
 * @brief Encode a tritri_target struct on a channel
 *
 * @param system_id ID of this system
 * @param component_id ID of this component (e.g. 200 for IMU)
 * @param chan The MAVLink channel this message will be sent over
 * @param msg The MAVLink message to compress the data into
 * @param tritri_target C-struct to read the message contents from
 */
static inline uint16_t mavlink_msg_tritri_target_encode_chan(uint32_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t* msg, const mavlink_tritri_target_t* tritri_target)
{
    return mavlink_msg_tritri_target_pack_chan(system_id, component_id, chan, msg, tritri_target->time_usec, tritri_target->target_time_usec, tritri_target->track_uid, tritri_target->target_name, tritri_target->target_id, tritri_target->target_set_id, tritri_target->flags, tritri_target->lat, tritri_target->lon, tritri_target->alt, tritri_target->vx, tritri_target->vy, tritri_target->vz, tritri_target->cov_pos_x, tritri_target->cov_pos_y, tritri_target->cov_pos_z, tritri_target->cov_vel_x, tritri_target->cov_vel_y, tritri_target->cov_vel_z, tritri_target->confidence, tritri_target->target_class, tritri_target->target_domain, tritri_target->target_force, tritri_target->sensor_type, tritri_target->tle_category, tritri_target->restricted_target_flags);
}

/**
 * @brief Encode a tritri_target struct with provided status structure
 *
 * @param system_id ID of this system
 * @param component_id ID of this component (e.g. 200 for IMU)
 * @param status MAVLink status structure
 * @param msg The MAVLink message to compress the data into
 * @param tritri_target C-struct to read the message contents from
 */
static inline uint16_t mavlink_msg_tritri_target_encode_status(uint32_t system_id, uint8_t component_id, mavlink_status_t* _status, mavlink_message_t* msg, const mavlink_tritri_target_t* tritri_target)
{
    return mavlink_msg_tritri_target_pack_status(system_id, component_id, _status, msg,  tritri_target->time_usec, tritri_target->target_time_usec, tritri_target->track_uid, tritri_target->target_name, tritri_target->target_id, tritri_target->target_set_id, tritri_target->flags, tritri_target->lat, tritri_target->lon, tritri_target->alt, tritri_target->vx, tritri_target->vy, tritri_target->vz, tritri_target->cov_pos_x, tritri_target->cov_pos_y, tritri_target->cov_pos_z, tritri_target->cov_vel_x, tritri_target->cov_vel_y, tritri_target->cov_vel_z, tritri_target->confidence, tritri_target->target_class, tritri_target->target_domain, tritri_target->target_force, tritri_target->sensor_type, tritri_target->tle_category, tritri_target->restricted_target_flags);
}

/**
 * @brief Send a tritri_target message
 * @param chan MAVLink channel to send the message
 *
 * @param time_usec [us] Timestamp (UNIX epoch, microseconds UTC).
 * @param target_time_usec [us] Timestamp when the target fix was valid (UNIX epoch, microseconds UTC).
 * @param track_uid  Track UID correlating to TRITRI_TRACK. All-zero if unknown.
 * @param target_name  Short human-readable callsign (null-terminated).
 * @param target_id  Unique target identifier generated by the source system.
 * @param target_set_id  Parent target set identifier. 0 = none.
 * @param flags  Target warning and status flags.
 * @param lat [degE7] Target latitude, WGS84. INT32_MAX if unknown.
 * @param lon [degE7] Target longitude, WGS84. INT32_MAX if unknown.
 * @param alt [m] Target altitude, MSL. NaN if unknown.
 * @param vx [m/s] Velocity north (NED). NaN if unknown.
 * @param vy [m/s] Velocity east (NED). NaN if unknown.
 * @param vz [m/s] Velocity down (NED). NaN if unknown.
 * @param cov_pos_x  Position covariance, north axis (m^2). NaN if unknown.
 * @param cov_pos_y  Position covariance, east axis (m^2). NaN if unknown.
 * @param cov_pos_z  Position covariance, down axis (m^2). NaN if unknown.
 * @param cov_vel_x  Velocity covariance, north axis (m^2/s^2). NaN if unknown.
 * @param cov_vel_y  Velocity covariance, east axis (m^2/s^2). NaN if unknown.
 * @param cov_vel_z  Velocity covariance, down axis (m^2/s^2). NaN if unknown.
 * @param confidence  Classification or detection confidence scaled 0-10000.
 * @param target_class  Target classification.
 * @param target_domain  Primary operating domain.
 * @param target_force  Force affiliation.
 * @param sensor_type  Primary sensor source.
 * @param tle_category  Target-location-error category label. 0 if unset.
 * @param restricted_target_flags  No-strike / restricted / NFA flags. 0 if none.
 */
#ifdef MAVLINK_USE_CONVENIENCE_FUNCTIONS

static inline void mavlink_msg_tritri_target_send(mavlink_channel_t chan, uint64_t time_usec, uint64_t target_time_usec, const uint8_t *track_uid, const char *target_name, uint32_t target_id, uint32_t target_set_id, uint32_t flags, int32_t lat, int32_t lon, float alt, float vx, float vy, float vz, float cov_pos_x, float cov_pos_y, float cov_pos_z, float cov_vel_x, float cov_vel_y, float cov_vel_z, uint16_t confidence, uint8_t target_class, uint8_t target_domain, uint8_t target_force, uint8_t sensor_type, uint8_t tle_category, uint8_t restricted_target_flags)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    char buf[MAVLINK_MSG_ID_TRITRI_TARGET_LEN];
    _mav_put_uint64_t(buf, 0, time_usec);
    _mav_put_uint64_t(buf, 8, target_time_usec);
    _mav_put_uint32_t(buf, 16, target_id);
    _mav_put_uint32_t(buf, 20, target_set_id);
    _mav_put_uint32_t(buf, 24, flags);
    _mav_put_int32_t(buf, 28, lat);
    _mav_put_int32_t(buf, 32, lon);
    _mav_put_float(buf, 36, alt);
    _mav_put_float(buf, 40, vx);
    _mav_put_float(buf, 44, vy);
    _mav_put_float(buf, 48, vz);
    _mav_put_float(buf, 52, cov_pos_x);
    _mav_put_float(buf, 56, cov_pos_y);
    _mav_put_float(buf, 60, cov_pos_z);
    _mav_put_float(buf, 64, cov_vel_x);
    _mav_put_float(buf, 68, cov_vel_y);
    _mav_put_float(buf, 72, cov_vel_z);
    _mav_put_uint16_t(buf, 76, confidence);
    _mav_put_uint8_t(buf, 110, target_class);
    _mav_put_uint8_t(buf, 111, target_domain);
    _mav_put_uint8_t(buf, 112, target_force);
    _mav_put_uint8_t(buf, 113, sensor_type);
    _mav_put_uint8_t(buf, 114, tle_category);
    _mav_put_uint8_t(buf, 115, restricted_target_flags);
    _mav_put_uint8_t_array(buf, 78, track_uid, 16);
    _mav_put_char_array(buf, 94, target_name, 16);
    _mav_finalize_message_chan_send(chan, MAVLINK_MSG_ID_TRITRI_TARGET, buf, MAVLINK_MSG_ID_TRITRI_TARGET_MIN_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_CRC);
#else
    mavlink_tritri_target_t packet;
    packet.time_usec = time_usec;
    packet.target_time_usec = target_time_usec;
    packet.target_id = target_id;
    packet.target_set_id = target_set_id;
    packet.flags = flags;
    packet.lat = lat;
    packet.lon = lon;
    packet.alt = alt;
    packet.vx = vx;
    packet.vy = vy;
    packet.vz = vz;
    packet.cov_pos_x = cov_pos_x;
    packet.cov_pos_y = cov_pos_y;
    packet.cov_pos_z = cov_pos_z;
    packet.cov_vel_x = cov_vel_x;
    packet.cov_vel_y = cov_vel_y;
    packet.cov_vel_z = cov_vel_z;
    packet.confidence = confidence;
    packet.target_class = target_class;
    packet.target_domain = target_domain;
    packet.target_force = target_force;
    packet.sensor_type = sensor_type;
    packet.tle_category = tle_category;
    packet.restricted_target_flags = restricted_target_flags;
    mav_array_memcpy(packet.track_uid, track_uid, sizeof(uint8_t)*16);
    mav_array_memcpy(packet.target_name, target_name, sizeof(char)*16);
    _mav_finalize_message_chan_send(chan, MAVLINK_MSG_ID_TRITRI_TARGET, (const char *)&packet, MAVLINK_MSG_ID_TRITRI_TARGET_MIN_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_CRC);
#endif
}

/**
 * @brief Send a tritri_target message
 * @param chan MAVLink channel to send the message
 * @param struct The MAVLink struct to serialize
 */
static inline void mavlink_msg_tritri_target_send_struct(mavlink_channel_t chan, const mavlink_tritri_target_t* tritri_target)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    mavlink_msg_tritri_target_send(chan, tritri_target->time_usec, tritri_target->target_time_usec, tritri_target->track_uid, tritri_target->target_name, tritri_target->target_id, tritri_target->target_set_id, tritri_target->flags, tritri_target->lat, tritri_target->lon, tritri_target->alt, tritri_target->vx, tritri_target->vy, tritri_target->vz, tritri_target->cov_pos_x, tritri_target->cov_pos_y, tritri_target->cov_pos_z, tritri_target->cov_vel_x, tritri_target->cov_vel_y, tritri_target->cov_vel_z, tritri_target->confidence, tritri_target->target_class, tritri_target->target_domain, tritri_target->target_force, tritri_target->sensor_type, tritri_target->tle_category, tritri_target->restricted_target_flags);
#else
    _mav_finalize_message_chan_send(chan, MAVLINK_MSG_ID_TRITRI_TARGET, (const char *)tritri_target, MAVLINK_MSG_ID_TRITRI_TARGET_MIN_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_CRC);
#endif
}

#if MAVLINK_MSG_ID_TRITRI_TARGET_LEN <= MAVLINK_MAX_PAYLOAD_LEN
/*
  This variant of _send() can be used to save stack space by reusing
  memory from the receive buffer.  The caller provides a
  mavlink_message_t which is the size of a full mavlink message. This
  is usually the receive buffer for the channel, and allows a reply to an
  incoming message with minimum stack space usage.
 */
static inline void mavlink_msg_tritri_target_send_buf(mavlink_message_t *msgbuf, mavlink_channel_t chan,  uint64_t time_usec, uint64_t target_time_usec, const uint8_t *track_uid, const char *target_name, uint32_t target_id, uint32_t target_set_id, uint32_t flags, int32_t lat, int32_t lon, float alt, float vx, float vy, float vz, float cov_pos_x, float cov_pos_y, float cov_pos_z, float cov_vel_x, float cov_vel_y, float cov_vel_z, uint16_t confidence, uint8_t target_class, uint8_t target_domain, uint8_t target_force, uint8_t sensor_type, uint8_t tle_category, uint8_t restricted_target_flags)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    char *buf = (char *)msgbuf;
    _mav_put_uint64_t(buf, 0, time_usec);
    _mav_put_uint64_t(buf, 8, target_time_usec);
    _mav_put_uint32_t(buf, 16, target_id);
    _mav_put_uint32_t(buf, 20, target_set_id);
    _mav_put_uint32_t(buf, 24, flags);
    _mav_put_int32_t(buf, 28, lat);
    _mav_put_int32_t(buf, 32, lon);
    _mav_put_float(buf, 36, alt);
    _mav_put_float(buf, 40, vx);
    _mav_put_float(buf, 44, vy);
    _mav_put_float(buf, 48, vz);
    _mav_put_float(buf, 52, cov_pos_x);
    _mav_put_float(buf, 56, cov_pos_y);
    _mav_put_float(buf, 60, cov_pos_z);
    _mav_put_float(buf, 64, cov_vel_x);
    _mav_put_float(buf, 68, cov_vel_y);
    _mav_put_float(buf, 72, cov_vel_z);
    _mav_put_uint16_t(buf, 76, confidence);
    _mav_put_uint8_t(buf, 110, target_class);
    _mav_put_uint8_t(buf, 111, target_domain);
    _mav_put_uint8_t(buf, 112, target_force);
    _mav_put_uint8_t(buf, 113, sensor_type);
    _mav_put_uint8_t(buf, 114, tle_category);
    _mav_put_uint8_t(buf, 115, restricted_target_flags);
    _mav_put_uint8_t_array(buf, 78, track_uid, 16);
    _mav_put_char_array(buf, 94, target_name, 16);
    _mav_finalize_message_chan_send(chan, MAVLINK_MSG_ID_TRITRI_TARGET, buf, MAVLINK_MSG_ID_TRITRI_TARGET_MIN_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_CRC);
#else
    mavlink_tritri_target_t *packet = (mavlink_tritri_target_t *)msgbuf;
    packet->time_usec = time_usec;
    packet->target_time_usec = target_time_usec;
    packet->target_id = target_id;
    packet->target_set_id = target_set_id;
    packet->flags = flags;
    packet->lat = lat;
    packet->lon = lon;
    packet->alt = alt;
    packet->vx = vx;
    packet->vy = vy;
    packet->vz = vz;
    packet->cov_pos_x = cov_pos_x;
    packet->cov_pos_y = cov_pos_y;
    packet->cov_pos_z = cov_pos_z;
    packet->cov_vel_x = cov_vel_x;
    packet->cov_vel_y = cov_vel_y;
    packet->cov_vel_z = cov_vel_z;
    packet->confidence = confidence;
    packet->target_class = target_class;
    packet->target_domain = target_domain;
    packet->target_force = target_force;
    packet->sensor_type = sensor_type;
    packet->tle_category = tle_category;
    packet->restricted_target_flags = restricted_target_flags;
    mav_array_memcpy(packet->track_uid, track_uid, sizeof(uint8_t)*16);
    mav_array_memcpy(packet->target_name, target_name, sizeof(char)*16);
    _mav_finalize_message_chan_send(chan, MAVLINK_MSG_ID_TRITRI_TARGET, (const char *)packet, MAVLINK_MSG_ID_TRITRI_TARGET_MIN_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_LEN, MAVLINK_MSG_ID_TRITRI_TARGET_CRC);
#endif
}
#endif

#endif

// MESSAGE TRITRI_TARGET UNPACKING


/**
 * @brief Get field time_usec from tritri_target message
 *
 * @return [us] Timestamp (UNIX epoch, microseconds UTC).
 */
static inline uint64_t mavlink_msg_tritri_target_get_time_usec(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint64_t(msg,  0);
}

/**
 * @brief Get field target_time_usec from tritri_target message
 *
 * @return [us] Timestamp when the target fix was valid (UNIX epoch, microseconds UTC).
 */
static inline uint64_t mavlink_msg_tritri_target_get_target_time_usec(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint64_t(msg,  8);
}

/**
 * @brief Get field track_uid from tritri_target message
 *
 * @return  Track UID correlating to TRITRI_TRACK. All-zero if unknown.
 */
static inline uint16_t mavlink_msg_tritri_target_get_track_uid(const mavlink_message_t* msg, uint8_t *track_uid)
{
    return _MAV_RETURN_uint8_t_array(msg, track_uid, 16,  78);
}

/**
 * @brief Get field target_name from tritri_target message
 *
 * @return  Short human-readable callsign (null-terminated).
 */
static inline uint16_t mavlink_msg_tritri_target_get_target_name(const mavlink_message_t* msg, char *target_name)
{
    return _MAV_RETURN_char_array(msg, target_name, 16,  94);
}

/**
 * @brief Get field target_id from tritri_target message
 *
 * @return  Unique target identifier generated by the source system.
 */
static inline uint32_t mavlink_msg_tritri_target_get_target_id(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint32_t(msg,  16);
}

/**
 * @brief Get field target_set_id from tritri_target message
 *
 * @return  Parent target set identifier. 0 = none.
 */
static inline uint32_t mavlink_msg_tritri_target_get_target_set_id(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint32_t(msg,  20);
}

/**
 * @brief Get field flags from tritri_target message
 *
 * @return  Target warning and status flags.
 */
static inline uint32_t mavlink_msg_tritri_target_get_flags(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint32_t(msg,  24);
}

/**
 * @brief Get field lat from tritri_target message
 *
 * @return [degE7] Target latitude, WGS84. INT32_MAX if unknown.
 */
static inline int32_t mavlink_msg_tritri_target_get_lat(const mavlink_message_t* msg)
{
    return _MAV_RETURN_int32_t(msg,  28);
}

/**
 * @brief Get field lon from tritri_target message
 *
 * @return [degE7] Target longitude, WGS84. INT32_MAX if unknown.
 */
static inline int32_t mavlink_msg_tritri_target_get_lon(const mavlink_message_t* msg)
{
    return _MAV_RETURN_int32_t(msg,  32);
}

/**
 * @brief Get field alt from tritri_target message
 *
 * @return [m] Target altitude, MSL. NaN if unknown.
 */
static inline float mavlink_msg_tritri_target_get_alt(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  36);
}

/**
 * @brief Get field vx from tritri_target message
 *
 * @return [m/s] Velocity north (NED). NaN if unknown.
 */
static inline float mavlink_msg_tritri_target_get_vx(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  40);
}

/**
 * @brief Get field vy from tritri_target message
 *
 * @return [m/s] Velocity east (NED). NaN if unknown.
 */
static inline float mavlink_msg_tritri_target_get_vy(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  44);
}

/**
 * @brief Get field vz from tritri_target message
 *
 * @return [m/s] Velocity down (NED). NaN if unknown.
 */
static inline float mavlink_msg_tritri_target_get_vz(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  48);
}

/**
 * @brief Get field cov_pos_x from tritri_target message
 *
 * @return  Position covariance, north axis (m^2). NaN if unknown.
 */
static inline float mavlink_msg_tritri_target_get_cov_pos_x(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  52);
}

/**
 * @brief Get field cov_pos_y from tritri_target message
 *
 * @return  Position covariance, east axis (m^2). NaN if unknown.
 */
static inline float mavlink_msg_tritri_target_get_cov_pos_y(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  56);
}

/**
 * @brief Get field cov_pos_z from tritri_target message
 *
 * @return  Position covariance, down axis (m^2). NaN if unknown.
 */
static inline float mavlink_msg_tritri_target_get_cov_pos_z(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  60);
}

/**
 * @brief Get field cov_vel_x from tritri_target message
 *
 * @return  Velocity covariance, north axis (m^2/s^2). NaN if unknown.
 */
static inline float mavlink_msg_tritri_target_get_cov_vel_x(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  64);
}

/**
 * @brief Get field cov_vel_y from tritri_target message
 *
 * @return  Velocity covariance, east axis (m^2/s^2). NaN if unknown.
 */
static inline float mavlink_msg_tritri_target_get_cov_vel_y(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  68);
}

/**
 * @brief Get field cov_vel_z from tritri_target message
 *
 * @return  Velocity covariance, down axis (m^2/s^2). NaN if unknown.
 */
static inline float mavlink_msg_tritri_target_get_cov_vel_z(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  72);
}

/**
 * @brief Get field confidence from tritri_target message
 *
 * @return  Classification or detection confidence scaled 0-10000.
 */
static inline uint16_t mavlink_msg_tritri_target_get_confidence(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint16_t(msg,  76);
}

/**
 * @brief Get field target_class from tritri_target message
 *
 * @return  Target classification.
 */
static inline uint8_t mavlink_msg_tritri_target_get_target_class(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  110);
}

/**
 * @brief Get field target_domain from tritri_target message
 *
 * @return  Primary operating domain.
 */
static inline uint8_t mavlink_msg_tritri_target_get_target_domain(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  111);
}

/**
 * @brief Get field target_force from tritri_target message
 *
 * @return  Force affiliation.
 */
static inline uint8_t mavlink_msg_tritri_target_get_target_force(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  112);
}

/**
 * @brief Get field sensor_type from tritri_target message
 *
 * @return  Primary sensor source.
 */
static inline uint8_t mavlink_msg_tritri_target_get_sensor_type(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  113);
}

/**
 * @brief Get field tle_category from tritri_target message
 *
 * @return  Target-location-error category label. 0 if unset.
 */
static inline uint8_t mavlink_msg_tritri_target_get_tle_category(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  114);
}

/**
 * @brief Get field restricted_target_flags from tritri_target message
 *
 * @return  No-strike / restricted / NFA flags. 0 if none.
 */
static inline uint8_t mavlink_msg_tritri_target_get_restricted_target_flags(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  115);
}

/**
 * @brief Decode a tritri_target message into a struct
 *
 * @param msg The message to decode
 * @param tritri_target C-struct to decode the message contents into
 */
static inline void mavlink_msg_tritri_target_decode(const mavlink_message_t* msg, mavlink_tritri_target_t* tritri_target)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    tritri_target->time_usec = mavlink_msg_tritri_target_get_time_usec(msg);
    tritri_target->target_time_usec = mavlink_msg_tritri_target_get_target_time_usec(msg);
    tritri_target->target_id = mavlink_msg_tritri_target_get_target_id(msg);
    tritri_target->target_set_id = mavlink_msg_tritri_target_get_target_set_id(msg);
    tritri_target->flags = mavlink_msg_tritri_target_get_flags(msg);
    tritri_target->lat = mavlink_msg_tritri_target_get_lat(msg);
    tritri_target->lon = mavlink_msg_tritri_target_get_lon(msg);
    tritri_target->alt = mavlink_msg_tritri_target_get_alt(msg);
    tritri_target->vx = mavlink_msg_tritri_target_get_vx(msg);
    tritri_target->vy = mavlink_msg_tritri_target_get_vy(msg);
    tritri_target->vz = mavlink_msg_tritri_target_get_vz(msg);
    tritri_target->cov_pos_x = mavlink_msg_tritri_target_get_cov_pos_x(msg);
    tritri_target->cov_pos_y = mavlink_msg_tritri_target_get_cov_pos_y(msg);
    tritri_target->cov_pos_z = mavlink_msg_tritri_target_get_cov_pos_z(msg);
    tritri_target->cov_vel_x = mavlink_msg_tritri_target_get_cov_vel_x(msg);
    tritri_target->cov_vel_y = mavlink_msg_tritri_target_get_cov_vel_y(msg);
    tritri_target->cov_vel_z = mavlink_msg_tritri_target_get_cov_vel_z(msg);
    tritri_target->confidence = mavlink_msg_tritri_target_get_confidence(msg);
    mavlink_msg_tritri_target_get_track_uid(msg, tritri_target->track_uid);
    mavlink_msg_tritri_target_get_target_name(msg, tritri_target->target_name);
    tritri_target->target_class = mavlink_msg_tritri_target_get_target_class(msg);
    tritri_target->target_domain = mavlink_msg_tritri_target_get_target_domain(msg);
    tritri_target->target_force = mavlink_msg_tritri_target_get_target_force(msg);
    tritri_target->sensor_type = mavlink_msg_tritri_target_get_sensor_type(msg);
    tritri_target->tle_category = mavlink_msg_tritri_target_get_tle_category(msg);
    tritri_target->restricted_target_flags = mavlink_msg_tritri_target_get_restricted_target_flags(msg);
#else
        uint8_t len = msg->len < MAVLINK_MSG_ID_TRITRI_TARGET_LEN? msg->len : MAVLINK_MSG_ID_TRITRI_TARGET_LEN;
        memset(tritri_target, 0, MAVLINK_MSG_ID_TRITRI_TARGET_LEN);
    memcpy(tritri_target, _MAV_PAYLOAD(msg), len);
#endif

}
