#pragma once
// MESSAGE TARGET PACKING

#include <stdint.h>

#define MAVLINK_MSG_ID_TARGET 53010


typedef struct __mavlink_target_t {
 uint64_t time_usec; /*< [us] Timestamp (UNIX epoch, microseconds UTC).*/
 uint64_t target_time_usec; /*< [us] Timestamp when the target was detected or designated (UNIX epoch, microseconds UTC).*/
 uint32_t target_id; /*<  Unique target identifier generated by the source system.*/
 uint32_t target_set_id; /*<  Parent target set identifier.*/
 uint32_t package_id_hash; /*<  Compact hash or identifier for the associated target package. 0 if no package is associated.*/
 int32_t lat; /*< [degE7] Target latitude, WGS84.*/
 int32_t lon; /*< [degE7] Target longitude, WGS84.*/
 float alt; /*< [m] Target altitude, MSL.*/
 float vx; /*< [m/s] Velocity north component (NED).*/
 float vy; /*< [m/s] Velocity east component (NED).*/
 float vz; /*< [m/s] Velocity down component (NED).*/
 float cov_pos_x; /*<  Position covariance, north axis (m^2).*/
 float cov_pos_y; /*<  Position covariance, east axis (m^2).*/
 float cov_pos_z; /*<  Position covariance, down axis (m^2).*/
 float cov_vel_x; /*<  Velocity covariance, north axis (m^2/s^2).*/
 float cov_vel_y; /*<  Velocity covariance, east axis (m^2/s^2).*/
 float cov_vel_z; /*<  Velocity covariance, down axis (m^2/s^2).*/
 float cep_desired; /*< [m] Desired circular error probable.*/
 float cep_max; /*< [m] Maximum acceptable circular error probable.*/
 uint32_t flags; /*<  Target warning and status flags.*/
 uint32_t package_endpoint_ip_1; /*<  Primary IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d; for example, 192.168.1.10 is 0xC0A8010A. 0 if unused.*/
 uint32_t package_endpoint_ip_2; /*<  Secondary IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d. 0 if unused.*/
 uint32_t package_endpoint_ip_3; /*<  Third IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d. 0 if unused.*/
 uint16_t confidence; /*<  Classification or detection confidence scaled from 0 to 10000, where 0 = 0.0 and 10000 = 1.0.*/
 uint16_t package_endpoint_port; /*<  TCP port for target package retrieval. 0 if no package is associated.*/
 uint16_t prf_code; /*<  Laser designator PRF code for SAL engagement (e.g. 1111-1788). 0 = no laser code assigned.*/
 char target_name[50]; /*<  Human-readable target name (null-terminated).*/
 uint8_t target_class; /*<  Target classification.*/
 uint8_t target_domain; /*<  Primary operating domain of the target.*/
 uint8_t target_entity_2525d; /*<  Optional MIL-STD-2525D land target entity refinement. UNKNOWN if not provided or not a land entity.*/
 uint8_t target_force; /*<  Force affiliation.*/
 uint8_t sensor_type; /*<  Primary sensor source used for target identification.*/
 uint8_t package_transport; /*<  Transport protocol used to retrieve the target package.*/
 char package_path[80]; /*<  Path component for target package retrieval, null-terminated. Empty if no package is associated.*/
 uint8_t tle_category; /*<  Target-location-error category (label only, not a mensuration figure).*/
 uint8_t dmpi_reference_kind; /*<  How the DMPI reference is expressed. A mensurated DMPI tied to a weapon solution is NOT carried.*/
 uint8_t restricted_target_flags; /*<  No-strike / restricted-target / no-fire-area context flags (bitmask).*/
} mavlink_target_t;

#define MAVLINK_MSG_ID_TARGET_LEN 245
#define MAVLINK_MSG_ID_TARGET_MIN_LEN 245
#define MAVLINK_MSG_ID_53010_LEN 245
#define MAVLINK_MSG_ID_53010_MIN_LEN 245

#define MAVLINK_MSG_ID_TARGET_CRC 71
#define MAVLINK_MSG_ID_53010_CRC 71

#define MAVLINK_MSG_TARGET_FIELD_TARGET_NAME_LEN 50
#define MAVLINK_MSG_TARGET_FIELD_PACKAGE_PATH_LEN 80

#if MAVLINK_COMMAND_24BIT
#define MAVLINK_MESSAGE_INFO_TARGET { \
    53010, \
    "TARGET", \
    37, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_target_t, time_usec) }, \
         { "target_time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 8, offsetof(mavlink_target_t, target_time_usec) }, \
         { "target_id", NULL, MAVLINK_TYPE_UINT32_T, 0, 16, offsetof(mavlink_target_t, target_id) }, \
         { "target_set_id", NULL, MAVLINK_TYPE_UINT32_T, 0, 20, offsetof(mavlink_target_t, target_set_id) }, \
         { "package_id_hash", NULL, MAVLINK_TYPE_UINT32_T, 0, 24, offsetof(mavlink_target_t, package_id_hash) }, \
         { "target_name", NULL, MAVLINK_TYPE_CHAR, 50, 106, offsetof(mavlink_target_t, target_name) }, \
         { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 28, offsetof(mavlink_target_t, lat) }, \
         { "lon", NULL, MAVLINK_TYPE_INT32_T, 0, 32, offsetof(mavlink_target_t, lon) }, \
         { "alt", NULL, MAVLINK_TYPE_FLOAT, 0, 36, offsetof(mavlink_target_t, alt) }, \
         { "vx", NULL, MAVLINK_TYPE_FLOAT, 0, 40, offsetof(mavlink_target_t, vx) }, \
         { "vy", NULL, MAVLINK_TYPE_FLOAT, 0, 44, offsetof(mavlink_target_t, vy) }, \
         { "vz", NULL, MAVLINK_TYPE_FLOAT, 0, 48, offsetof(mavlink_target_t, vz) }, \
         { "cov_pos_x", NULL, MAVLINK_TYPE_FLOAT, 0, 52, offsetof(mavlink_target_t, cov_pos_x) }, \
         { "cov_pos_y", NULL, MAVLINK_TYPE_FLOAT, 0, 56, offsetof(mavlink_target_t, cov_pos_y) }, \
         { "cov_pos_z", NULL, MAVLINK_TYPE_FLOAT, 0, 60, offsetof(mavlink_target_t, cov_pos_z) }, \
         { "cov_vel_x", NULL, MAVLINK_TYPE_FLOAT, 0, 64, offsetof(mavlink_target_t, cov_vel_x) }, \
         { "cov_vel_y", NULL, MAVLINK_TYPE_FLOAT, 0, 68, offsetof(mavlink_target_t, cov_vel_y) }, \
         { "cov_vel_z", NULL, MAVLINK_TYPE_FLOAT, 0, 72, offsetof(mavlink_target_t, cov_vel_z) }, \
         { "cep_desired", NULL, MAVLINK_TYPE_FLOAT, 0, 76, offsetof(mavlink_target_t, cep_desired) }, \
         { "cep_max", NULL, MAVLINK_TYPE_FLOAT, 0, 80, offsetof(mavlink_target_t, cep_max) }, \
         { "flags", NULL, MAVLINK_TYPE_UINT32_T, 0, 84, offsetof(mavlink_target_t, flags) }, \
         { "package_endpoint_ip_1", NULL, MAVLINK_TYPE_UINT32_T, 0, 88, offsetof(mavlink_target_t, package_endpoint_ip_1) }, \
         { "package_endpoint_ip_2", NULL, MAVLINK_TYPE_UINT32_T, 0, 92, offsetof(mavlink_target_t, package_endpoint_ip_2) }, \
         { "package_endpoint_ip_3", NULL, MAVLINK_TYPE_UINT32_T, 0, 96, offsetof(mavlink_target_t, package_endpoint_ip_3) }, \
         { "target_class", NULL, MAVLINK_TYPE_UINT8_T, 0, 156, offsetof(mavlink_target_t, target_class) }, \
         { "target_domain", NULL, MAVLINK_TYPE_UINT8_T, 0, 157, offsetof(mavlink_target_t, target_domain) }, \
         { "target_entity_2525d", NULL, MAVLINK_TYPE_UINT8_T, 0, 158, offsetof(mavlink_target_t, target_entity_2525d) }, \
         { "target_force", NULL, MAVLINK_TYPE_UINT8_T, 0, 159, offsetof(mavlink_target_t, target_force) }, \
         { "confidence", NULL, MAVLINK_TYPE_UINT16_T, 0, 100, offsetof(mavlink_target_t, confidence) }, \
         { "package_endpoint_port", NULL, MAVLINK_TYPE_UINT16_T, 0, 102, offsetof(mavlink_target_t, package_endpoint_port) }, \
         { "sensor_type", NULL, MAVLINK_TYPE_UINT8_T, 0, 160, offsetof(mavlink_target_t, sensor_type) }, \
         { "package_transport", NULL, MAVLINK_TYPE_UINT8_T, 0, 161, offsetof(mavlink_target_t, package_transport) }, \
         { "package_path", NULL, MAVLINK_TYPE_CHAR, 80, 162, offsetof(mavlink_target_t, package_path) }, \
         { "prf_code", NULL, MAVLINK_TYPE_UINT16_T, 0, 104, offsetof(mavlink_target_t, prf_code) }, \
         { "tle_category", NULL, MAVLINK_TYPE_UINT8_T, 0, 242, offsetof(mavlink_target_t, tle_category) }, \
         { "dmpi_reference_kind", NULL, MAVLINK_TYPE_UINT8_T, 0, 243, offsetof(mavlink_target_t, dmpi_reference_kind) }, \
         { "restricted_target_flags", NULL, MAVLINK_TYPE_UINT8_T, 0, 244, offsetof(mavlink_target_t, restricted_target_flags) }, \
         } \
}
#else
#define MAVLINK_MESSAGE_INFO_TARGET { \
    "TARGET", \
    37, \
    {  { "time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_target_t, time_usec) }, \
         { "target_time_usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 8, offsetof(mavlink_target_t, target_time_usec) }, \
         { "target_id", NULL, MAVLINK_TYPE_UINT32_T, 0, 16, offsetof(mavlink_target_t, target_id) }, \
         { "target_set_id", NULL, MAVLINK_TYPE_UINT32_T, 0, 20, offsetof(mavlink_target_t, target_set_id) }, \
         { "package_id_hash", NULL, MAVLINK_TYPE_UINT32_T, 0, 24, offsetof(mavlink_target_t, package_id_hash) }, \
         { "target_name", NULL, MAVLINK_TYPE_CHAR, 50, 106, offsetof(mavlink_target_t, target_name) }, \
         { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 28, offsetof(mavlink_target_t, lat) }, \
         { "lon", NULL, MAVLINK_TYPE_INT32_T, 0, 32, offsetof(mavlink_target_t, lon) }, \
         { "alt", NULL, MAVLINK_TYPE_FLOAT, 0, 36, offsetof(mavlink_target_t, alt) }, \
         { "vx", NULL, MAVLINK_TYPE_FLOAT, 0, 40, offsetof(mavlink_target_t, vx) }, \
         { "vy", NULL, MAVLINK_TYPE_FLOAT, 0, 44, offsetof(mavlink_target_t, vy) }, \
         { "vz", NULL, MAVLINK_TYPE_FLOAT, 0, 48, offsetof(mavlink_target_t, vz) }, \
         { "cov_pos_x", NULL, MAVLINK_TYPE_FLOAT, 0, 52, offsetof(mavlink_target_t, cov_pos_x) }, \
         { "cov_pos_y", NULL, MAVLINK_TYPE_FLOAT, 0, 56, offsetof(mavlink_target_t, cov_pos_y) }, \
         { "cov_pos_z", NULL, MAVLINK_TYPE_FLOAT, 0, 60, offsetof(mavlink_target_t, cov_pos_z) }, \
         { "cov_vel_x", NULL, MAVLINK_TYPE_FLOAT, 0, 64, offsetof(mavlink_target_t, cov_vel_x) }, \
         { "cov_vel_y", NULL, MAVLINK_TYPE_FLOAT, 0, 68, offsetof(mavlink_target_t, cov_vel_y) }, \
         { "cov_vel_z", NULL, MAVLINK_TYPE_FLOAT, 0, 72, offsetof(mavlink_target_t, cov_vel_z) }, \
         { "cep_desired", NULL, MAVLINK_TYPE_FLOAT, 0, 76, offsetof(mavlink_target_t, cep_desired) }, \
         { "cep_max", NULL, MAVLINK_TYPE_FLOAT, 0, 80, offsetof(mavlink_target_t, cep_max) }, \
         { "flags", NULL, MAVLINK_TYPE_UINT32_T, 0, 84, offsetof(mavlink_target_t, flags) }, \
         { "package_endpoint_ip_1", NULL, MAVLINK_TYPE_UINT32_T, 0, 88, offsetof(mavlink_target_t, package_endpoint_ip_1) }, \
         { "package_endpoint_ip_2", NULL, MAVLINK_TYPE_UINT32_T, 0, 92, offsetof(mavlink_target_t, package_endpoint_ip_2) }, \
         { "package_endpoint_ip_3", NULL, MAVLINK_TYPE_UINT32_T, 0, 96, offsetof(mavlink_target_t, package_endpoint_ip_3) }, \
         { "target_class", NULL, MAVLINK_TYPE_UINT8_T, 0, 156, offsetof(mavlink_target_t, target_class) }, \
         { "target_domain", NULL, MAVLINK_TYPE_UINT8_T, 0, 157, offsetof(mavlink_target_t, target_domain) }, \
         { "target_entity_2525d", NULL, MAVLINK_TYPE_UINT8_T, 0, 158, offsetof(mavlink_target_t, target_entity_2525d) }, \
         { "target_force", NULL, MAVLINK_TYPE_UINT8_T, 0, 159, offsetof(mavlink_target_t, target_force) }, \
         { "confidence", NULL, MAVLINK_TYPE_UINT16_T, 0, 100, offsetof(mavlink_target_t, confidence) }, \
         { "package_endpoint_port", NULL, MAVLINK_TYPE_UINT16_T, 0, 102, offsetof(mavlink_target_t, package_endpoint_port) }, \
         { "sensor_type", NULL, MAVLINK_TYPE_UINT8_T, 0, 160, offsetof(mavlink_target_t, sensor_type) }, \
         { "package_transport", NULL, MAVLINK_TYPE_UINT8_T, 0, 161, offsetof(mavlink_target_t, package_transport) }, \
         { "package_path", NULL, MAVLINK_TYPE_CHAR, 80, 162, offsetof(mavlink_target_t, package_path) }, \
         { "prf_code", NULL, MAVLINK_TYPE_UINT16_T, 0, 104, offsetof(mavlink_target_t, prf_code) }, \
         { "tle_category", NULL, MAVLINK_TYPE_UINT8_T, 0, 242, offsetof(mavlink_target_t, tle_category) }, \
         { "dmpi_reference_kind", NULL, MAVLINK_TYPE_UINT8_T, 0, 243, offsetof(mavlink_target_t, dmpi_reference_kind) }, \
         { "restricted_target_flags", NULL, MAVLINK_TYPE_UINT8_T, 0, 244, offsetof(mavlink_target_t, restricted_target_flags) }, \
         } \
}
#endif

/**
 * @brief Pack a target message
 * @param system_id ID of this system
 * @param component_id ID of this component (e.g. 200 for IMU)
 * @param msg The MAVLink message to compress the data into
 *
 * @param time_usec [us] Timestamp (UNIX epoch, microseconds UTC).
 * @param target_time_usec [us] Timestamp when the target was detected or designated (UNIX epoch, microseconds UTC).
 * @param target_id  Unique target identifier generated by the source system.
 * @param target_set_id  Parent target set identifier.
 * @param package_id_hash  Compact hash or identifier for the associated target package. 0 if no package is associated.
 * @param target_name  Human-readable target name (null-terminated).
 * @param lat [degE7] Target latitude, WGS84.
 * @param lon [degE7] Target longitude, WGS84.
 * @param alt [m] Target altitude, MSL.
 * @param vx [m/s] Velocity north component (NED).
 * @param vy [m/s] Velocity east component (NED).
 * @param vz [m/s] Velocity down component (NED).
 * @param cov_pos_x  Position covariance, north axis (m^2).
 * @param cov_pos_y  Position covariance, east axis (m^2).
 * @param cov_pos_z  Position covariance, down axis (m^2).
 * @param cov_vel_x  Velocity covariance, north axis (m^2/s^2).
 * @param cov_vel_y  Velocity covariance, east axis (m^2/s^2).
 * @param cov_vel_z  Velocity covariance, down axis (m^2/s^2).
 * @param cep_desired [m] Desired circular error probable.
 * @param cep_max [m] Maximum acceptable circular error probable.
 * @param flags  Target warning and status flags.
 * @param package_endpoint_ip_1  Primary IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d; for example, 192.168.1.10 is 0xC0A8010A. 0 if unused.
 * @param package_endpoint_ip_2  Secondary IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d. 0 if unused.
 * @param package_endpoint_ip_3  Third IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d. 0 if unused.
 * @param target_class  Target classification.
 * @param target_domain  Primary operating domain of the target.
 * @param target_entity_2525d  Optional MIL-STD-2525D land target entity refinement. UNKNOWN if not provided or not a land entity.
 * @param target_force  Force affiliation.
 * @param confidence  Classification or detection confidence scaled from 0 to 10000, where 0 = 0.0 and 10000 = 1.0.
 * @param package_endpoint_port  TCP port for target package retrieval. 0 if no package is associated.
 * @param sensor_type  Primary sensor source used for target identification.
 * @param package_transport  Transport protocol used to retrieve the target package.
 * @param package_path  Path component for target package retrieval, null-terminated. Empty if no package is associated.
 * @param prf_code  Laser designator PRF code for SAL engagement (e.g. 1111-1788). 0 = no laser code assigned.
 * @param tle_category  Target-location-error category (label only, not a mensuration figure).
 * @param dmpi_reference_kind  How the DMPI reference is expressed. A mensurated DMPI tied to a weapon solution is NOT carried.
 * @param restricted_target_flags  No-strike / restricted-target / no-fire-area context flags (bitmask).
 * @return length of the message in bytes (excluding serial stream start sign)
 */
static inline uint16_t mavlink_msg_target_pack(uint32_t system_id, uint8_t component_id, mavlink_message_t* msg,
                               uint64_t time_usec, uint64_t target_time_usec, uint32_t target_id, uint32_t target_set_id, uint32_t package_id_hash, const char *target_name, int32_t lat, int32_t lon, float alt, float vx, float vy, float vz, float cov_pos_x, float cov_pos_y, float cov_pos_z, float cov_vel_x, float cov_vel_y, float cov_vel_z, float cep_desired, float cep_max, uint32_t flags, uint32_t package_endpoint_ip_1, uint32_t package_endpoint_ip_2, uint32_t package_endpoint_ip_3, uint8_t target_class, uint8_t target_domain, uint8_t target_entity_2525d, uint8_t target_force, uint16_t confidence, uint16_t package_endpoint_port, uint8_t sensor_type, uint8_t package_transport, const char *package_path, uint16_t prf_code, uint8_t tle_category, uint8_t dmpi_reference_kind, uint8_t restricted_target_flags)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    char buf[MAVLINK_MSG_ID_TARGET_LEN];
    _mav_put_uint64_t(buf, 0, time_usec);
    _mav_put_uint64_t(buf, 8, target_time_usec);
    _mav_put_uint32_t(buf, 16, target_id);
    _mav_put_uint32_t(buf, 20, target_set_id);
    _mav_put_uint32_t(buf, 24, package_id_hash);
    _mav_put_int32_t(buf, 28, lat);
    _mav_put_int32_t(buf, 32, lon);
    _mav_put_float(buf, 36, alt);
    _mav_put_float(buf, 40, vx);
    _mav_put_float(buf, 44, vy);
    _mav_put_float(buf, 48, vz);
    _mav_put_float(buf, 52, cov_pos_x);
    _mav_put_float(buf, 56, cov_pos_y);
    _mav_put_float(buf, 60, cov_pos_z);
    _mav_put_float(buf, 64, cov_vel_x);
    _mav_put_float(buf, 68, cov_vel_y);
    _mav_put_float(buf, 72, cov_vel_z);
    _mav_put_float(buf, 76, cep_desired);
    _mav_put_float(buf, 80, cep_max);
    _mav_put_uint32_t(buf, 84, flags);
    _mav_put_uint32_t(buf, 88, package_endpoint_ip_1);
    _mav_put_uint32_t(buf, 92, package_endpoint_ip_2);
    _mav_put_uint32_t(buf, 96, package_endpoint_ip_3);
    _mav_put_uint16_t(buf, 100, confidence);
    _mav_put_uint16_t(buf, 102, package_endpoint_port);
    _mav_put_uint16_t(buf, 104, prf_code);
    _mav_put_uint8_t(buf, 156, target_class);
    _mav_put_uint8_t(buf, 157, target_domain);
    _mav_put_uint8_t(buf, 158, target_entity_2525d);
    _mav_put_uint8_t(buf, 159, target_force);
    _mav_put_uint8_t(buf, 160, sensor_type);
    _mav_put_uint8_t(buf, 161, package_transport);
    _mav_put_uint8_t(buf, 242, tle_category);
    _mav_put_uint8_t(buf, 243, dmpi_reference_kind);
    _mav_put_uint8_t(buf, 244, restricted_target_flags);
    _mav_put_char_array(buf, 106, target_name, 50);
    _mav_put_char_array(buf, 162, package_path, 80);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), buf, MAVLINK_MSG_ID_TARGET_LEN);
#else
    mavlink_target_t packet;
    packet.time_usec = time_usec;
    packet.target_time_usec = target_time_usec;
    packet.target_id = target_id;
    packet.target_set_id = target_set_id;
    packet.package_id_hash = package_id_hash;
    packet.lat = lat;
    packet.lon = lon;
    packet.alt = alt;
    packet.vx = vx;
    packet.vy = vy;
    packet.vz = vz;
    packet.cov_pos_x = cov_pos_x;
    packet.cov_pos_y = cov_pos_y;
    packet.cov_pos_z = cov_pos_z;
    packet.cov_vel_x = cov_vel_x;
    packet.cov_vel_y = cov_vel_y;
    packet.cov_vel_z = cov_vel_z;
    packet.cep_desired = cep_desired;
    packet.cep_max = cep_max;
    packet.flags = flags;
    packet.package_endpoint_ip_1 = package_endpoint_ip_1;
    packet.package_endpoint_ip_2 = package_endpoint_ip_2;
    packet.package_endpoint_ip_3 = package_endpoint_ip_3;
    packet.confidence = confidence;
    packet.package_endpoint_port = package_endpoint_port;
    packet.prf_code = prf_code;
    packet.target_class = target_class;
    packet.target_domain = target_domain;
    packet.target_entity_2525d = target_entity_2525d;
    packet.target_force = target_force;
    packet.sensor_type = sensor_type;
    packet.package_transport = package_transport;
    packet.tle_category = tle_category;
    packet.dmpi_reference_kind = dmpi_reference_kind;
    packet.restricted_target_flags = restricted_target_flags;
    mav_array_memcpy(packet.target_name, target_name, sizeof(char)*50);
    mav_array_memcpy(packet.package_path, package_path, sizeof(char)*80);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), &packet, MAVLINK_MSG_ID_TARGET_LEN);
#endif

    msg->msgid = MAVLINK_MSG_ID_TARGET;
    return mavlink_finalize_message(msg, system_id, component_id, MAVLINK_MSG_ID_TARGET_MIN_LEN, MAVLINK_MSG_ID_TARGET_LEN, MAVLINK_MSG_ID_TARGET_CRC);
}

/**
 * @brief Pack a target message
 * @param system_id ID of this system
 * @param component_id ID of this component (e.g. 200 for IMU)
 * @param status MAVLink status structure
 * @param msg The MAVLink message to compress the data into
 *
 * @param time_usec [us] Timestamp (UNIX epoch, microseconds UTC).
 * @param target_time_usec [us] Timestamp when the target was detected or designated (UNIX epoch, microseconds UTC).
 * @param target_id  Unique target identifier generated by the source system.
 * @param target_set_id  Parent target set identifier.
 * @param package_id_hash  Compact hash or identifier for the associated target package. 0 if no package is associated.
 * @param target_name  Human-readable target name (null-terminated).
 * @param lat [degE7] Target latitude, WGS84.
 * @param lon [degE7] Target longitude, WGS84.
 * @param alt [m] Target altitude, MSL.
 * @param vx [m/s] Velocity north component (NED).
 * @param vy [m/s] Velocity east component (NED).
 * @param vz [m/s] Velocity down component (NED).
 * @param cov_pos_x  Position covariance, north axis (m^2).
 * @param cov_pos_y  Position covariance, east axis (m^2).
 * @param cov_pos_z  Position covariance, down axis (m^2).
 * @param cov_vel_x  Velocity covariance, north axis (m^2/s^2).
 * @param cov_vel_y  Velocity covariance, east axis (m^2/s^2).
 * @param cov_vel_z  Velocity covariance, down axis (m^2/s^2).
 * @param cep_desired [m] Desired circular error probable.
 * @param cep_max [m] Maximum acceptable circular error probable.
 * @param flags  Target warning and status flags.
 * @param package_endpoint_ip_1  Primary IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d; for example, 192.168.1.10 is 0xC0A8010A. 0 if unused.
 * @param package_endpoint_ip_2  Secondary IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d. 0 if unused.
 * @param package_endpoint_ip_3  Third IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d. 0 if unused.
 * @param target_class  Target classification.
 * @param target_domain  Primary operating domain of the target.
 * @param target_entity_2525d  Optional MIL-STD-2525D land target entity refinement. UNKNOWN if not provided or not a land entity.
 * @param target_force  Force affiliation.
 * @param confidence  Classification or detection confidence scaled from 0 to 10000, where 0 = 0.0 and 10000 = 1.0.
 * @param package_endpoint_port  TCP port for target package retrieval. 0 if no package is associated.
 * @param sensor_type  Primary sensor source used for target identification.
 * @param package_transport  Transport protocol used to retrieve the target package.
 * @param package_path  Path component for target package retrieval, null-terminated. Empty if no package is associated.
 * @param prf_code  Laser designator PRF code for SAL engagement (e.g. 1111-1788). 0 = no laser code assigned.
 * @param tle_category  Target-location-error category (label only, not a mensuration figure).
 * @param dmpi_reference_kind  How the DMPI reference is expressed. A mensurated DMPI tied to a weapon solution is NOT carried.
 * @param restricted_target_flags  No-strike / restricted-target / no-fire-area context flags (bitmask).
 * @return length of the message in bytes (excluding serial stream start sign)
 */
static inline uint16_t mavlink_msg_target_pack_status(uint32_t system_id, uint8_t component_id, mavlink_status_t *_status, mavlink_message_t* msg,
                               uint64_t time_usec, uint64_t target_time_usec, uint32_t target_id, uint32_t target_set_id, uint32_t package_id_hash, const char *target_name, int32_t lat, int32_t lon, float alt, float vx, float vy, float vz, float cov_pos_x, float cov_pos_y, float cov_pos_z, float cov_vel_x, float cov_vel_y, float cov_vel_z, float cep_desired, float cep_max, uint32_t flags, uint32_t package_endpoint_ip_1, uint32_t package_endpoint_ip_2, uint32_t package_endpoint_ip_3, uint8_t target_class, uint8_t target_domain, uint8_t target_entity_2525d, uint8_t target_force, uint16_t confidence, uint16_t package_endpoint_port, uint8_t sensor_type, uint8_t package_transport, const char *package_path, uint16_t prf_code, uint8_t tle_category, uint8_t dmpi_reference_kind, uint8_t restricted_target_flags)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    char buf[MAVLINK_MSG_ID_TARGET_LEN];
    _mav_put_uint64_t(buf, 0, time_usec);
    _mav_put_uint64_t(buf, 8, target_time_usec);
    _mav_put_uint32_t(buf, 16, target_id);
    _mav_put_uint32_t(buf, 20, target_set_id);
    _mav_put_uint32_t(buf, 24, package_id_hash);
    _mav_put_int32_t(buf, 28, lat);
    _mav_put_int32_t(buf, 32, lon);
    _mav_put_float(buf, 36, alt);
    _mav_put_float(buf, 40, vx);
    _mav_put_float(buf, 44, vy);
    _mav_put_float(buf, 48, vz);
    _mav_put_float(buf, 52, cov_pos_x);
    _mav_put_float(buf, 56, cov_pos_y);
    _mav_put_float(buf, 60, cov_pos_z);
    _mav_put_float(buf, 64, cov_vel_x);
    _mav_put_float(buf, 68, cov_vel_y);
    _mav_put_float(buf, 72, cov_vel_z);
    _mav_put_float(buf, 76, cep_desired);
    _mav_put_float(buf, 80, cep_max);
    _mav_put_uint32_t(buf, 84, flags);
    _mav_put_uint32_t(buf, 88, package_endpoint_ip_1);
    _mav_put_uint32_t(buf, 92, package_endpoint_ip_2);
    _mav_put_uint32_t(buf, 96, package_endpoint_ip_3);
    _mav_put_uint16_t(buf, 100, confidence);
    _mav_put_uint16_t(buf, 102, package_endpoint_port);
    _mav_put_uint16_t(buf, 104, prf_code);
    _mav_put_uint8_t(buf, 156, target_class);
    _mav_put_uint8_t(buf, 157, target_domain);
    _mav_put_uint8_t(buf, 158, target_entity_2525d);
    _mav_put_uint8_t(buf, 159, target_force);
    _mav_put_uint8_t(buf, 160, sensor_type);
    _mav_put_uint8_t(buf, 161, package_transport);
    _mav_put_uint8_t(buf, 242, tle_category);
    _mav_put_uint8_t(buf, 243, dmpi_reference_kind);
    _mav_put_uint8_t(buf, 244, restricted_target_flags);
    _mav_put_char_array(buf, 106, target_name, 50);
    _mav_put_char_array(buf, 162, package_path, 80);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), buf, MAVLINK_MSG_ID_TARGET_LEN);
#else
    mavlink_target_t packet;
    packet.time_usec = time_usec;
    packet.target_time_usec = target_time_usec;
    packet.target_id = target_id;
    packet.target_set_id = target_set_id;
    packet.package_id_hash = package_id_hash;
    packet.lat = lat;
    packet.lon = lon;
    packet.alt = alt;
    packet.vx = vx;
    packet.vy = vy;
    packet.vz = vz;
    packet.cov_pos_x = cov_pos_x;
    packet.cov_pos_y = cov_pos_y;
    packet.cov_pos_z = cov_pos_z;
    packet.cov_vel_x = cov_vel_x;
    packet.cov_vel_y = cov_vel_y;
    packet.cov_vel_z = cov_vel_z;
    packet.cep_desired = cep_desired;
    packet.cep_max = cep_max;
    packet.flags = flags;
    packet.package_endpoint_ip_1 = package_endpoint_ip_1;
    packet.package_endpoint_ip_2 = package_endpoint_ip_2;
    packet.package_endpoint_ip_3 = package_endpoint_ip_3;
    packet.confidence = confidence;
    packet.package_endpoint_port = package_endpoint_port;
    packet.prf_code = prf_code;
    packet.target_class = target_class;
    packet.target_domain = target_domain;
    packet.target_entity_2525d = target_entity_2525d;
    packet.target_force = target_force;
    packet.sensor_type = sensor_type;
    packet.package_transport = package_transport;
    packet.tle_category = tle_category;
    packet.dmpi_reference_kind = dmpi_reference_kind;
    packet.restricted_target_flags = restricted_target_flags;
    mav_array_memcpy(packet.target_name, target_name, sizeof(char)*50);
    mav_array_memcpy(packet.package_path, package_path, sizeof(char)*80);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), &packet, MAVLINK_MSG_ID_TARGET_LEN);
#endif

    msg->msgid = MAVLINK_MSG_ID_TARGET;
#if MAVLINK_CRC_EXTRA
    return mavlink_finalize_message_buffer(msg, system_id, component_id, _status, MAVLINK_MSG_ID_TARGET_MIN_LEN, MAVLINK_MSG_ID_TARGET_LEN, MAVLINK_MSG_ID_TARGET_CRC);
#else
    return mavlink_finalize_message_buffer(msg, system_id, component_id, _status, MAVLINK_MSG_ID_TARGET_MIN_LEN, MAVLINK_MSG_ID_TARGET_LEN, 0);
#endif
}

/**
 * @brief Pack a target message on a channel
 * @param system_id ID of this system
 * @param component_id ID of this component (e.g. 200 for IMU)
 * @param chan The MAVLink channel this message will be sent over
 * @param msg The MAVLink message to compress the data into
 * @param time_usec [us] Timestamp (UNIX epoch, microseconds UTC).
 * @param target_time_usec [us] Timestamp when the target was detected or designated (UNIX epoch, microseconds UTC).
 * @param target_id  Unique target identifier generated by the source system.
 * @param target_set_id  Parent target set identifier.
 * @param package_id_hash  Compact hash or identifier for the associated target package. 0 if no package is associated.
 * @param target_name  Human-readable target name (null-terminated).
 * @param lat [degE7] Target latitude, WGS84.
 * @param lon [degE7] Target longitude, WGS84.
 * @param alt [m] Target altitude, MSL.
 * @param vx [m/s] Velocity north component (NED).
 * @param vy [m/s] Velocity east component (NED).
 * @param vz [m/s] Velocity down component (NED).
 * @param cov_pos_x  Position covariance, north axis (m^2).
 * @param cov_pos_y  Position covariance, east axis (m^2).
 * @param cov_pos_z  Position covariance, down axis (m^2).
 * @param cov_vel_x  Velocity covariance, north axis (m^2/s^2).
 * @param cov_vel_y  Velocity covariance, east axis (m^2/s^2).
 * @param cov_vel_z  Velocity covariance, down axis (m^2/s^2).
 * @param cep_desired [m] Desired circular error probable.
 * @param cep_max [m] Maximum acceptable circular error probable.
 * @param flags  Target warning and status flags.
 * @param package_endpoint_ip_1  Primary IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d; for example, 192.168.1.10 is 0xC0A8010A. 0 if unused.
 * @param package_endpoint_ip_2  Secondary IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d. 0 if unused.
 * @param package_endpoint_ip_3  Third IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d. 0 if unused.
 * @param target_class  Target classification.
 * @param target_domain  Primary operating domain of the target.
 * @param target_entity_2525d  Optional MIL-STD-2525D land target entity refinement. UNKNOWN if not provided or not a land entity.
 * @param target_force  Force affiliation.
 * @param confidence  Classification or detection confidence scaled from 0 to 10000, where 0 = 0.0 and 10000 = 1.0.
 * @param package_endpoint_port  TCP port for target package retrieval. 0 if no package is associated.
 * @param sensor_type  Primary sensor source used for target identification.
 * @param package_transport  Transport protocol used to retrieve the target package.
 * @param package_path  Path component for target package retrieval, null-terminated. Empty if no package is associated.
 * @param prf_code  Laser designator PRF code for SAL engagement (e.g. 1111-1788). 0 = no laser code assigned.
 * @param tle_category  Target-location-error category (label only, not a mensuration figure).
 * @param dmpi_reference_kind  How the DMPI reference is expressed. A mensurated DMPI tied to a weapon solution is NOT carried.
 * @param restricted_target_flags  No-strike / restricted-target / no-fire-area context flags (bitmask).
 * @return length of the message in bytes (excluding serial stream start sign)
 */
static inline uint16_t mavlink_msg_target_pack_chan(uint32_t system_id, uint8_t component_id, uint8_t chan,
                               mavlink_message_t* msg,
                                   uint64_t time_usec,uint64_t target_time_usec,uint32_t target_id,uint32_t target_set_id,uint32_t package_id_hash,const char *target_name,int32_t lat,int32_t lon,float alt,float vx,float vy,float vz,float cov_pos_x,float cov_pos_y,float cov_pos_z,float cov_vel_x,float cov_vel_y,float cov_vel_z,float cep_desired,float cep_max,uint32_t flags,uint32_t package_endpoint_ip_1,uint32_t package_endpoint_ip_2,uint32_t package_endpoint_ip_3,uint8_t target_class,uint8_t target_domain,uint8_t target_entity_2525d,uint8_t target_force,uint16_t confidence,uint16_t package_endpoint_port,uint8_t sensor_type,uint8_t package_transport,const char *package_path,uint16_t prf_code,uint8_t tle_category,uint8_t dmpi_reference_kind,uint8_t restricted_target_flags)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    char buf[MAVLINK_MSG_ID_TARGET_LEN];
    _mav_put_uint64_t(buf, 0, time_usec);
    _mav_put_uint64_t(buf, 8, target_time_usec);
    _mav_put_uint32_t(buf, 16, target_id);
    _mav_put_uint32_t(buf, 20, target_set_id);
    _mav_put_uint32_t(buf, 24, package_id_hash);
    _mav_put_int32_t(buf, 28, lat);
    _mav_put_int32_t(buf, 32, lon);
    _mav_put_float(buf, 36, alt);
    _mav_put_float(buf, 40, vx);
    _mav_put_float(buf, 44, vy);
    _mav_put_float(buf, 48, vz);
    _mav_put_float(buf, 52, cov_pos_x);
    _mav_put_float(buf, 56, cov_pos_y);
    _mav_put_float(buf, 60, cov_pos_z);
    _mav_put_float(buf, 64, cov_vel_x);
    _mav_put_float(buf, 68, cov_vel_y);
    _mav_put_float(buf, 72, cov_vel_z);
    _mav_put_float(buf, 76, cep_desired);
    _mav_put_float(buf, 80, cep_max);
    _mav_put_uint32_t(buf, 84, flags);
    _mav_put_uint32_t(buf, 88, package_endpoint_ip_1);
    _mav_put_uint32_t(buf, 92, package_endpoint_ip_2);
    _mav_put_uint32_t(buf, 96, package_endpoint_ip_3);
    _mav_put_uint16_t(buf, 100, confidence);
    _mav_put_uint16_t(buf, 102, package_endpoint_port);
    _mav_put_uint16_t(buf, 104, prf_code);
    _mav_put_uint8_t(buf, 156, target_class);
    _mav_put_uint8_t(buf, 157, target_domain);
    _mav_put_uint8_t(buf, 158, target_entity_2525d);
    _mav_put_uint8_t(buf, 159, target_force);
    _mav_put_uint8_t(buf, 160, sensor_type);
    _mav_put_uint8_t(buf, 161, package_transport);
    _mav_put_uint8_t(buf, 242, tle_category);
    _mav_put_uint8_t(buf, 243, dmpi_reference_kind);
    _mav_put_uint8_t(buf, 244, restricted_target_flags);
    _mav_put_char_array(buf, 106, target_name, 50);
    _mav_put_char_array(buf, 162, package_path, 80);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), buf, MAVLINK_MSG_ID_TARGET_LEN);
#else
    mavlink_target_t packet;
    packet.time_usec = time_usec;
    packet.target_time_usec = target_time_usec;
    packet.target_id = target_id;
    packet.target_set_id = target_set_id;
    packet.package_id_hash = package_id_hash;
    packet.lat = lat;
    packet.lon = lon;
    packet.alt = alt;
    packet.vx = vx;
    packet.vy = vy;
    packet.vz = vz;
    packet.cov_pos_x = cov_pos_x;
    packet.cov_pos_y = cov_pos_y;
    packet.cov_pos_z = cov_pos_z;
    packet.cov_vel_x = cov_vel_x;
    packet.cov_vel_y = cov_vel_y;
    packet.cov_vel_z = cov_vel_z;
    packet.cep_desired = cep_desired;
    packet.cep_max = cep_max;
    packet.flags = flags;
    packet.package_endpoint_ip_1 = package_endpoint_ip_1;
    packet.package_endpoint_ip_2 = package_endpoint_ip_2;
    packet.package_endpoint_ip_3 = package_endpoint_ip_3;
    packet.confidence = confidence;
    packet.package_endpoint_port = package_endpoint_port;
    packet.prf_code = prf_code;
    packet.target_class = target_class;
    packet.target_domain = target_domain;
    packet.target_entity_2525d = target_entity_2525d;
    packet.target_force = target_force;
    packet.sensor_type = sensor_type;
    packet.package_transport = package_transport;
    packet.tle_category = tle_category;
    packet.dmpi_reference_kind = dmpi_reference_kind;
    packet.restricted_target_flags = restricted_target_flags;
    mav_array_memcpy(packet.target_name, target_name, sizeof(char)*50);
    mav_array_memcpy(packet.package_path, package_path, sizeof(char)*80);
        memcpy(_MAV_PAYLOAD_NON_CONST(msg), &packet, MAVLINK_MSG_ID_TARGET_LEN);
#endif

    msg->msgid = MAVLINK_MSG_ID_TARGET;
    return mavlink_finalize_message_chan(msg, system_id, component_id, chan, MAVLINK_MSG_ID_TARGET_MIN_LEN, MAVLINK_MSG_ID_TARGET_LEN, MAVLINK_MSG_ID_TARGET_CRC);
}

/**
 * @brief Encode a target struct
 *
 * @param system_id ID of this system
 * @param component_id ID of this component (e.g. 200 for IMU)
 * @param msg The MAVLink message to compress the data into
 * @param target C-struct to read the message contents from
 */
static inline uint16_t mavlink_msg_target_encode(uint32_t system_id, uint8_t component_id, mavlink_message_t* msg, const mavlink_target_t* target)
{
    return mavlink_msg_target_pack(system_id, component_id, msg, target->time_usec, target->target_time_usec, target->target_id, target->target_set_id, target->package_id_hash, target->target_name, target->lat, target->lon, target->alt, target->vx, target->vy, target->vz, target->cov_pos_x, target->cov_pos_y, target->cov_pos_z, target->cov_vel_x, target->cov_vel_y, target->cov_vel_z, target->cep_desired, target->cep_max, target->flags, target->package_endpoint_ip_1, target->package_endpoint_ip_2, target->package_endpoint_ip_3, target->target_class, target->target_domain, target->target_entity_2525d, target->target_force, target->confidence, target->package_endpoint_port, target->sensor_type, target->package_transport, target->package_path, target->prf_code, target->tle_category, target->dmpi_reference_kind, target->restricted_target_flags);
}

/**
 * @brief Encode a target struct on a channel
 *
 * @param system_id ID of this system
 * @param component_id ID of this component (e.g. 200 for IMU)
 * @param chan The MAVLink channel this message will be sent over
 * @param msg The MAVLink message to compress the data into
 * @param target C-struct to read the message contents from
 */
static inline uint16_t mavlink_msg_target_encode_chan(uint32_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t* msg, const mavlink_target_t* target)
{
    return mavlink_msg_target_pack_chan(system_id, component_id, chan, msg, target->time_usec, target->target_time_usec, target->target_id, target->target_set_id, target->package_id_hash, target->target_name, target->lat, target->lon, target->alt, target->vx, target->vy, target->vz, target->cov_pos_x, target->cov_pos_y, target->cov_pos_z, target->cov_vel_x, target->cov_vel_y, target->cov_vel_z, target->cep_desired, target->cep_max, target->flags, target->package_endpoint_ip_1, target->package_endpoint_ip_2, target->package_endpoint_ip_3, target->target_class, target->target_domain, target->target_entity_2525d, target->target_force, target->confidence, target->package_endpoint_port, target->sensor_type, target->package_transport, target->package_path, target->prf_code, target->tle_category, target->dmpi_reference_kind, target->restricted_target_flags);
}

/**
 * @brief Encode a target struct with provided status structure
 *
 * @param system_id ID of this system
 * @param component_id ID of this component (e.g. 200 for IMU)
 * @param status MAVLink status structure
 * @param msg The MAVLink message to compress the data into
 * @param target C-struct to read the message contents from
 */
static inline uint16_t mavlink_msg_target_encode_status(uint32_t system_id, uint8_t component_id, mavlink_status_t* _status, mavlink_message_t* msg, const mavlink_target_t* target)
{
    return mavlink_msg_target_pack_status(system_id, component_id, _status, msg,  target->time_usec, target->target_time_usec, target->target_id, target->target_set_id, target->package_id_hash, target->target_name, target->lat, target->lon, target->alt, target->vx, target->vy, target->vz, target->cov_pos_x, target->cov_pos_y, target->cov_pos_z, target->cov_vel_x, target->cov_vel_y, target->cov_vel_z, target->cep_desired, target->cep_max, target->flags, target->package_endpoint_ip_1, target->package_endpoint_ip_2, target->package_endpoint_ip_3, target->target_class, target->target_domain, target->target_entity_2525d, target->target_force, target->confidence, target->package_endpoint_port, target->sensor_type, target->package_transport, target->package_path, target->prf_code, target->tle_category, target->dmpi_reference_kind, target->restricted_target_flags);
}

/**
 * @brief Send a target message
 * @param chan MAVLink channel to send the message
 *
 * @param time_usec [us] Timestamp (UNIX epoch, microseconds UTC).
 * @param target_time_usec [us] Timestamp when the target was detected or designated (UNIX epoch, microseconds UTC).
 * @param target_id  Unique target identifier generated by the source system.
 * @param target_set_id  Parent target set identifier.
 * @param package_id_hash  Compact hash or identifier for the associated target package. 0 if no package is associated.
 * @param target_name  Human-readable target name (null-terminated).
 * @param lat [degE7] Target latitude, WGS84.
 * @param lon [degE7] Target longitude, WGS84.
 * @param alt [m] Target altitude, MSL.
 * @param vx [m/s] Velocity north component (NED).
 * @param vy [m/s] Velocity east component (NED).
 * @param vz [m/s] Velocity down component (NED).
 * @param cov_pos_x  Position covariance, north axis (m^2).
 * @param cov_pos_y  Position covariance, east axis (m^2).
 * @param cov_pos_z  Position covariance, down axis (m^2).
 * @param cov_vel_x  Velocity covariance, north axis (m^2/s^2).
 * @param cov_vel_y  Velocity covariance, east axis (m^2/s^2).
 * @param cov_vel_z  Velocity covariance, down axis (m^2/s^2).
 * @param cep_desired [m] Desired circular error probable.
 * @param cep_max [m] Maximum acceptable circular error probable.
 * @param flags  Target warning and status flags.
 * @param package_endpoint_ip_1  Primary IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d; for example, 192.168.1.10 is 0xC0A8010A. 0 if unused.
 * @param package_endpoint_ip_2  Secondary IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d. 0 if unused.
 * @param package_endpoint_ip_3  Third IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d. 0 if unused.
 * @param target_class  Target classification.
 * @param target_domain  Primary operating domain of the target.
 * @param target_entity_2525d  Optional MIL-STD-2525D land target entity refinement. UNKNOWN if not provided or not a land entity.
 * @param target_force  Force affiliation.
 * @param confidence  Classification or detection confidence scaled from 0 to 10000, where 0 = 0.0 and 10000 = 1.0.
 * @param package_endpoint_port  TCP port for target package retrieval. 0 if no package is associated.
 * @param sensor_type  Primary sensor source used for target identification.
 * @param package_transport  Transport protocol used to retrieve the target package.
 * @param package_path  Path component for target package retrieval, null-terminated. Empty if no package is associated.
 * @param prf_code  Laser designator PRF code for SAL engagement (e.g. 1111-1788). 0 = no laser code assigned.
 * @param tle_category  Target-location-error category (label only, not a mensuration figure).
 * @param dmpi_reference_kind  How the DMPI reference is expressed. A mensurated DMPI tied to a weapon solution is NOT carried.
 * @param restricted_target_flags  No-strike / restricted-target / no-fire-area context flags (bitmask).
 */
#ifdef MAVLINK_USE_CONVENIENCE_FUNCTIONS

static inline void mavlink_msg_target_send(mavlink_channel_t chan, uint64_t time_usec, uint64_t target_time_usec, uint32_t target_id, uint32_t target_set_id, uint32_t package_id_hash, const char *target_name, int32_t lat, int32_t lon, float alt, float vx, float vy, float vz, float cov_pos_x, float cov_pos_y, float cov_pos_z, float cov_vel_x, float cov_vel_y, float cov_vel_z, float cep_desired, float cep_max, uint32_t flags, uint32_t package_endpoint_ip_1, uint32_t package_endpoint_ip_2, uint32_t package_endpoint_ip_3, uint8_t target_class, uint8_t target_domain, uint8_t target_entity_2525d, uint8_t target_force, uint16_t confidence, uint16_t package_endpoint_port, uint8_t sensor_type, uint8_t package_transport, const char *package_path, uint16_t prf_code, uint8_t tle_category, uint8_t dmpi_reference_kind, uint8_t restricted_target_flags)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    char buf[MAVLINK_MSG_ID_TARGET_LEN];
    _mav_put_uint64_t(buf, 0, time_usec);
    _mav_put_uint64_t(buf, 8, target_time_usec);
    _mav_put_uint32_t(buf, 16, target_id);
    _mav_put_uint32_t(buf, 20, target_set_id);
    _mav_put_uint32_t(buf, 24, package_id_hash);
    _mav_put_int32_t(buf, 28, lat);
    _mav_put_int32_t(buf, 32, lon);
    _mav_put_float(buf, 36, alt);
    _mav_put_float(buf, 40, vx);
    _mav_put_float(buf, 44, vy);
    _mav_put_float(buf, 48, vz);
    _mav_put_float(buf, 52, cov_pos_x);
    _mav_put_float(buf, 56, cov_pos_y);
    _mav_put_float(buf, 60, cov_pos_z);
    _mav_put_float(buf, 64, cov_vel_x);
    _mav_put_float(buf, 68, cov_vel_y);
    _mav_put_float(buf, 72, cov_vel_z);
    _mav_put_float(buf, 76, cep_desired);
    _mav_put_float(buf, 80, cep_max);
    _mav_put_uint32_t(buf, 84, flags);
    _mav_put_uint32_t(buf, 88, package_endpoint_ip_1);
    _mav_put_uint32_t(buf, 92, package_endpoint_ip_2);
    _mav_put_uint32_t(buf, 96, package_endpoint_ip_3);
    _mav_put_uint16_t(buf, 100, confidence);
    _mav_put_uint16_t(buf, 102, package_endpoint_port);
    _mav_put_uint16_t(buf, 104, prf_code);
    _mav_put_uint8_t(buf, 156, target_class);
    _mav_put_uint8_t(buf, 157, target_domain);
    _mav_put_uint8_t(buf, 158, target_entity_2525d);
    _mav_put_uint8_t(buf, 159, target_force);
    _mav_put_uint8_t(buf, 160, sensor_type);
    _mav_put_uint8_t(buf, 161, package_transport);
    _mav_put_uint8_t(buf, 242, tle_category);
    _mav_put_uint8_t(buf, 243, dmpi_reference_kind);
    _mav_put_uint8_t(buf, 244, restricted_target_flags);
    _mav_put_char_array(buf, 106, target_name, 50);
    _mav_put_char_array(buf, 162, package_path, 80);
    _mav_finalize_message_chan_send(chan, MAVLINK_MSG_ID_TARGET, buf, MAVLINK_MSG_ID_TARGET_MIN_LEN, MAVLINK_MSG_ID_TARGET_LEN, MAVLINK_MSG_ID_TARGET_CRC);
#else
    mavlink_target_t packet;
    packet.time_usec = time_usec;
    packet.target_time_usec = target_time_usec;
    packet.target_id = target_id;
    packet.target_set_id = target_set_id;
    packet.package_id_hash = package_id_hash;
    packet.lat = lat;
    packet.lon = lon;
    packet.alt = alt;
    packet.vx = vx;
    packet.vy = vy;
    packet.vz = vz;
    packet.cov_pos_x = cov_pos_x;
    packet.cov_pos_y = cov_pos_y;
    packet.cov_pos_z = cov_pos_z;
    packet.cov_vel_x = cov_vel_x;
    packet.cov_vel_y = cov_vel_y;
    packet.cov_vel_z = cov_vel_z;
    packet.cep_desired = cep_desired;
    packet.cep_max = cep_max;
    packet.flags = flags;
    packet.package_endpoint_ip_1 = package_endpoint_ip_1;
    packet.package_endpoint_ip_2 = package_endpoint_ip_2;
    packet.package_endpoint_ip_3 = package_endpoint_ip_3;
    packet.confidence = confidence;
    packet.package_endpoint_port = package_endpoint_port;
    packet.prf_code = prf_code;
    packet.target_class = target_class;
    packet.target_domain = target_domain;
    packet.target_entity_2525d = target_entity_2525d;
    packet.target_force = target_force;
    packet.sensor_type = sensor_type;
    packet.package_transport = package_transport;
    packet.tle_category = tle_category;
    packet.dmpi_reference_kind = dmpi_reference_kind;
    packet.restricted_target_flags = restricted_target_flags;
    mav_array_memcpy(packet.target_name, target_name, sizeof(char)*50);
    mav_array_memcpy(packet.package_path, package_path, sizeof(char)*80);
    _mav_finalize_message_chan_send(chan, MAVLINK_MSG_ID_TARGET, (const char *)&packet, MAVLINK_MSG_ID_TARGET_MIN_LEN, MAVLINK_MSG_ID_TARGET_LEN, MAVLINK_MSG_ID_TARGET_CRC);
#endif
}

/**
 * @brief Send a target message
 * @param chan MAVLink channel to send the message
 * @param struct The MAVLink struct to serialize
 */
static inline void mavlink_msg_target_send_struct(mavlink_channel_t chan, const mavlink_target_t* target)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    mavlink_msg_target_send(chan, target->time_usec, target->target_time_usec, target->target_id, target->target_set_id, target->package_id_hash, target->target_name, target->lat, target->lon, target->alt, target->vx, target->vy, target->vz, target->cov_pos_x, target->cov_pos_y, target->cov_pos_z, target->cov_vel_x, target->cov_vel_y, target->cov_vel_z, target->cep_desired, target->cep_max, target->flags, target->package_endpoint_ip_1, target->package_endpoint_ip_2, target->package_endpoint_ip_3, target->target_class, target->target_domain, target->target_entity_2525d, target->target_force, target->confidence, target->package_endpoint_port, target->sensor_type, target->package_transport, target->package_path, target->prf_code, target->tle_category, target->dmpi_reference_kind, target->restricted_target_flags);
#else
    _mav_finalize_message_chan_send(chan, MAVLINK_MSG_ID_TARGET, (const char *)target, MAVLINK_MSG_ID_TARGET_MIN_LEN, MAVLINK_MSG_ID_TARGET_LEN, MAVLINK_MSG_ID_TARGET_CRC);
#endif
}

#if MAVLINK_MSG_ID_TARGET_LEN <= MAVLINK_MAX_PAYLOAD_LEN
/*
  This variant of _send() can be used to save stack space by reusing
  memory from the receive buffer.  The caller provides a
  mavlink_message_t which is the size of a full mavlink message. This
  is usually the receive buffer for the channel, and allows a reply to an
  incoming message with minimum stack space usage.
 */
static inline void mavlink_msg_target_send_buf(mavlink_message_t *msgbuf, mavlink_channel_t chan,  uint64_t time_usec, uint64_t target_time_usec, uint32_t target_id, uint32_t target_set_id, uint32_t package_id_hash, const char *target_name, int32_t lat, int32_t lon, float alt, float vx, float vy, float vz, float cov_pos_x, float cov_pos_y, float cov_pos_z, float cov_vel_x, float cov_vel_y, float cov_vel_z, float cep_desired, float cep_max, uint32_t flags, uint32_t package_endpoint_ip_1, uint32_t package_endpoint_ip_2, uint32_t package_endpoint_ip_3, uint8_t target_class, uint8_t target_domain, uint8_t target_entity_2525d, uint8_t target_force, uint16_t confidence, uint16_t package_endpoint_port, uint8_t sensor_type, uint8_t package_transport, const char *package_path, uint16_t prf_code, uint8_t tle_category, uint8_t dmpi_reference_kind, uint8_t restricted_target_flags)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    char *buf = (char *)msgbuf;
    _mav_put_uint64_t(buf, 0, time_usec);
    _mav_put_uint64_t(buf, 8, target_time_usec);
    _mav_put_uint32_t(buf, 16, target_id);
    _mav_put_uint32_t(buf, 20, target_set_id);
    _mav_put_uint32_t(buf, 24, package_id_hash);
    _mav_put_int32_t(buf, 28, lat);
    _mav_put_int32_t(buf, 32, lon);
    _mav_put_float(buf, 36, alt);
    _mav_put_float(buf, 40, vx);
    _mav_put_float(buf, 44, vy);
    _mav_put_float(buf, 48, vz);
    _mav_put_float(buf, 52, cov_pos_x);
    _mav_put_float(buf, 56, cov_pos_y);
    _mav_put_float(buf, 60, cov_pos_z);
    _mav_put_float(buf, 64, cov_vel_x);
    _mav_put_float(buf, 68, cov_vel_y);
    _mav_put_float(buf, 72, cov_vel_z);
    _mav_put_float(buf, 76, cep_desired);
    _mav_put_float(buf, 80, cep_max);
    _mav_put_uint32_t(buf, 84, flags);
    _mav_put_uint32_t(buf, 88, package_endpoint_ip_1);
    _mav_put_uint32_t(buf, 92, package_endpoint_ip_2);
    _mav_put_uint32_t(buf, 96, package_endpoint_ip_3);
    _mav_put_uint16_t(buf, 100, confidence);
    _mav_put_uint16_t(buf, 102, package_endpoint_port);
    _mav_put_uint16_t(buf, 104, prf_code);
    _mav_put_uint8_t(buf, 156, target_class);
    _mav_put_uint8_t(buf, 157, target_domain);
    _mav_put_uint8_t(buf, 158, target_entity_2525d);
    _mav_put_uint8_t(buf, 159, target_force);
    _mav_put_uint8_t(buf, 160, sensor_type);
    _mav_put_uint8_t(buf, 161, package_transport);
    _mav_put_uint8_t(buf, 242, tle_category);
    _mav_put_uint8_t(buf, 243, dmpi_reference_kind);
    _mav_put_uint8_t(buf, 244, restricted_target_flags);
    _mav_put_char_array(buf, 106, target_name, 50);
    _mav_put_char_array(buf, 162, package_path, 80);
    _mav_finalize_message_chan_send(chan, MAVLINK_MSG_ID_TARGET, buf, MAVLINK_MSG_ID_TARGET_MIN_LEN, MAVLINK_MSG_ID_TARGET_LEN, MAVLINK_MSG_ID_TARGET_CRC);
#else
    mavlink_target_t *packet = (mavlink_target_t *)msgbuf;
    packet->time_usec = time_usec;
    packet->target_time_usec = target_time_usec;
    packet->target_id = target_id;
    packet->target_set_id = target_set_id;
    packet->package_id_hash = package_id_hash;
    packet->lat = lat;
    packet->lon = lon;
    packet->alt = alt;
    packet->vx = vx;
    packet->vy = vy;
    packet->vz = vz;
    packet->cov_pos_x = cov_pos_x;
    packet->cov_pos_y = cov_pos_y;
    packet->cov_pos_z = cov_pos_z;
    packet->cov_vel_x = cov_vel_x;
    packet->cov_vel_y = cov_vel_y;
    packet->cov_vel_z = cov_vel_z;
    packet->cep_desired = cep_desired;
    packet->cep_max = cep_max;
    packet->flags = flags;
    packet->package_endpoint_ip_1 = package_endpoint_ip_1;
    packet->package_endpoint_ip_2 = package_endpoint_ip_2;
    packet->package_endpoint_ip_3 = package_endpoint_ip_3;
    packet->confidence = confidence;
    packet->package_endpoint_port = package_endpoint_port;
    packet->prf_code = prf_code;
    packet->target_class = target_class;
    packet->target_domain = target_domain;
    packet->target_entity_2525d = target_entity_2525d;
    packet->target_force = target_force;
    packet->sensor_type = sensor_type;
    packet->package_transport = package_transport;
    packet->tle_category = tle_category;
    packet->dmpi_reference_kind = dmpi_reference_kind;
    packet->restricted_target_flags = restricted_target_flags;
    mav_array_memcpy(packet->target_name, target_name, sizeof(char)*50);
    mav_array_memcpy(packet->package_path, package_path, sizeof(char)*80);
    _mav_finalize_message_chan_send(chan, MAVLINK_MSG_ID_TARGET, (const char *)packet, MAVLINK_MSG_ID_TARGET_MIN_LEN, MAVLINK_MSG_ID_TARGET_LEN, MAVLINK_MSG_ID_TARGET_CRC);
#endif
}
#endif

#endif

// MESSAGE TARGET UNPACKING


/**
 * @brief Get field time_usec from target message
 *
 * @return [us] Timestamp (UNIX epoch, microseconds UTC).
 */
static inline uint64_t mavlink_msg_target_get_time_usec(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint64_t(msg,  0);
}

/**
 * @brief Get field target_time_usec from target message
 *
 * @return [us] Timestamp when the target was detected or designated (UNIX epoch, microseconds UTC).
 */
static inline uint64_t mavlink_msg_target_get_target_time_usec(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint64_t(msg,  8);
}

/**
 * @brief Get field target_id from target message
 *
 * @return  Unique target identifier generated by the source system.
 */
static inline uint32_t mavlink_msg_target_get_target_id(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint32_t(msg,  16);
}

/**
 * @brief Get field target_set_id from target message
 *
 * @return  Parent target set identifier.
 */
static inline uint32_t mavlink_msg_target_get_target_set_id(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint32_t(msg,  20);
}

/**
 * @brief Get field package_id_hash from target message
 *
 * @return  Compact hash or identifier for the associated target package. 0 if no package is associated.
 */
static inline uint32_t mavlink_msg_target_get_package_id_hash(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint32_t(msg,  24);
}

/**
 * @brief Get field target_name from target message
 *
 * @return  Human-readable target name (null-terminated).
 */
static inline uint16_t mavlink_msg_target_get_target_name(const mavlink_message_t* msg, char *target_name)
{
    return _MAV_RETURN_char_array(msg, target_name, 50,  106);
}

/**
 * @brief Get field lat from target message
 *
 * @return [degE7] Target latitude, WGS84.
 */
static inline int32_t mavlink_msg_target_get_lat(const mavlink_message_t* msg)
{
    return _MAV_RETURN_int32_t(msg,  28);
}

/**
 * @brief Get field lon from target message
 *
 * @return [degE7] Target longitude, WGS84.
 */
static inline int32_t mavlink_msg_target_get_lon(const mavlink_message_t* msg)
{
    return _MAV_RETURN_int32_t(msg,  32);
}

/**
 * @brief Get field alt from target message
 *
 * @return [m] Target altitude, MSL.
 */
static inline float mavlink_msg_target_get_alt(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  36);
}

/**
 * @brief Get field vx from target message
 *
 * @return [m/s] Velocity north component (NED).
 */
static inline float mavlink_msg_target_get_vx(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  40);
}

/**
 * @brief Get field vy from target message
 *
 * @return [m/s] Velocity east component (NED).
 */
static inline float mavlink_msg_target_get_vy(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  44);
}

/**
 * @brief Get field vz from target message
 *
 * @return [m/s] Velocity down component (NED).
 */
static inline float mavlink_msg_target_get_vz(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  48);
}

/**
 * @brief Get field cov_pos_x from target message
 *
 * @return  Position covariance, north axis (m^2).
 */
static inline float mavlink_msg_target_get_cov_pos_x(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  52);
}

/**
 * @brief Get field cov_pos_y from target message
 *
 * @return  Position covariance, east axis (m^2).
 */
static inline float mavlink_msg_target_get_cov_pos_y(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  56);
}

/**
 * @brief Get field cov_pos_z from target message
 *
 * @return  Position covariance, down axis (m^2).
 */
static inline float mavlink_msg_target_get_cov_pos_z(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  60);
}

/**
 * @brief Get field cov_vel_x from target message
 *
 * @return  Velocity covariance, north axis (m^2/s^2).
 */
static inline float mavlink_msg_target_get_cov_vel_x(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  64);
}

/**
 * @brief Get field cov_vel_y from target message
 *
 * @return  Velocity covariance, east axis (m^2/s^2).
 */
static inline float mavlink_msg_target_get_cov_vel_y(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  68);
}

/**
 * @brief Get field cov_vel_z from target message
 *
 * @return  Velocity covariance, down axis (m^2/s^2).
 */
static inline float mavlink_msg_target_get_cov_vel_z(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  72);
}

/**
 * @brief Get field cep_desired from target message
 *
 * @return [m] Desired circular error probable.
 */
static inline float mavlink_msg_target_get_cep_desired(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  76);
}

/**
 * @brief Get field cep_max from target message
 *
 * @return [m] Maximum acceptable circular error probable.
 */
static inline float mavlink_msg_target_get_cep_max(const mavlink_message_t* msg)
{
    return _MAV_RETURN_float(msg,  80);
}

/**
 * @brief Get field flags from target message
 *
 * @return  Target warning and status flags.
 */
static inline uint32_t mavlink_msg_target_get_flags(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint32_t(msg,  84);
}

/**
 * @brief Get field package_endpoint_ip_1 from target message
 *
 * @return  Primary IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d; for example, 192.168.1.10 is 0xC0A8010A. 0 if unused.
 */
static inline uint32_t mavlink_msg_target_get_package_endpoint_ip_1(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint32_t(msg,  88);
}

/**
 * @brief Get field package_endpoint_ip_2 from target message
 *
 * @return  Secondary IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d. 0 if unused.
 */
static inline uint32_t mavlink_msg_target_get_package_endpoint_ip_2(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint32_t(msg,  92);
}

/**
 * @brief Get field package_endpoint_ip_3 from target message
 *
 * @return  Third IPv4 endpoint address for target package retrieval, packed as (a<<24)|(b<<16)|(c<<8)|d for address a.b.c.d. 0 if unused.
 */
static inline uint32_t mavlink_msg_target_get_package_endpoint_ip_3(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint32_t(msg,  96);
}

/**
 * @brief Get field target_class from target message
 *
 * @return  Target classification.
 */
static inline uint8_t mavlink_msg_target_get_target_class(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  156);
}

/**
 * @brief Get field target_domain from target message
 *
 * @return  Primary operating domain of the target.
 */
static inline uint8_t mavlink_msg_target_get_target_domain(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  157);
}

/**
 * @brief Get field target_entity_2525d from target message
 *
 * @return  Optional MIL-STD-2525D land target entity refinement. UNKNOWN if not provided or not a land entity.
 */
static inline uint8_t mavlink_msg_target_get_target_entity_2525d(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  158);
}

/**
 * @brief Get field target_force from target message
 *
 * @return  Force affiliation.
 */
static inline uint8_t mavlink_msg_target_get_target_force(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  159);
}

/**
 * @brief Get field confidence from target message
 *
 * @return  Classification or detection confidence scaled from 0 to 10000, where 0 = 0.0 and 10000 = 1.0.
 */
static inline uint16_t mavlink_msg_target_get_confidence(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint16_t(msg,  100);
}

/**
 * @brief Get field package_endpoint_port from target message
 *
 * @return  TCP port for target package retrieval. 0 if no package is associated.
 */
static inline uint16_t mavlink_msg_target_get_package_endpoint_port(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint16_t(msg,  102);
}

/**
 * @brief Get field sensor_type from target message
 *
 * @return  Primary sensor source used for target identification.
 */
static inline uint8_t mavlink_msg_target_get_sensor_type(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  160);
}

/**
 * @brief Get field package_transport from target message
 *
 * @return  Transport protocol used to retrieve the target package.
 */
static inline uint8_t mavlink_msg_target_get_package_transport(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  161);
}

/**
 * @brief Get field package_path from target message
 *
 * @return  Path component for target package retrieval, null-terminated. Empty if no package is associated.
 */
static inline uint16_t mavlink_msg_target_get_package_path(const mavlink_message_t* msg, char *package_path)
{
    return _MAV_RETURN_char_array(msg, package_path, 80,  162);
}

/**
 * @brief Get field prf_code from target message
 *
 * @return  Laser designator PRF code for SAL engagement (e.g. 1111-1788). 0 = no laser code assigned.
 */
static inline uint16_t mavlink_msg_target_get_prf_code(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint16_t(msg,  104);
}

/**
 * @brief Get field tle_category from target message
 *
 * @return  Target-location-error category (label only, not a mensuration figure).
 */
static inline uint8_t mavlink_msg_target_get_tle_category(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  242);
}

/**
 * @brief Get field dmpi_reference_kind from target message
 *
 * @return  How the DMPI reference is expressed. A mensurated DMPI tied to a weapon solution is NOT carried.
 */
static inline uint8_t mavlink_msg_target_get_dmpi_reference_kind(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  243);
}

/**
 * @brief Get field restricted_target_flags from target message
 *
 * @return  No-strike / restricted-target / no-fire-area context flags (bitmask).
 */
static inline uint8_t mavlink_msg_target_get_restricted_target_flags(const mavlink_message_t* msg)
{
    return _MAV_RETURN_uint8_t(msg,  244);
}

/**
 * @brief Decode a target message into a struct
 *
 * @param msg The message to decode
 * @param target C-struct to decode the message contents into
 */
static inline void mavlink_msg_target_decode(const mavlink_message_t* msg, mavlink_target_t* target)
{
#if MAVLINK_NEED_BYTE_SWAP || !MAVLINK_ALIGNED_FIELDS
    target->time_usec = mavlink_msg_target_get_time_usec(msg);
    target->target_time_usec = mavlink_msg_target_get_target_time_usec(msg);
    target->target_id = mavlink_msg_target_get_target_id(msg);
    target->target_set_id = mavlink_msg_target_get_target_set_id(msg);
    target->package_id_hash = mavlink_msg_target_get_package_id_hash(msg);
    target->lat = mavlink_msg_target_get_lat(msg);
    target->lon = mavlink_msg_target_get_lon(msg);
    target->alt = mavlink_msg_target_get_alt(msg);
    target->vx = mavlink_msg_target_get_vx(msg);
    target->vy = mavlink_msg_target_get_vy(msg);
    target->vz = mavlink_msg_target_get_vz(msg);
    target->cov_pos_x = mavlink_msg_target_get_cov_pos_x(msg);
    target->cov_pos_y = mavlink_msg_target_get_cov_pos_y(msg);
    target->cov_pos_z = mavlink_msg_target_get_cov_pos_z(msg);
    target->cov_vel_x = mavlink_msg_target_get_cov_vel_x(msg);
    target->cov_vel_y = mavlink_msg_target_get_cov_vel_y(msg);
    target->cov_vel_z = mavlink_msg_target_get_cov_vel_z(msg);
    target->cep_desired = mavlink_msg_target_get_cep_desired(msg);
    target->cep_max = mavlink_msg_target_get_cep_max(msg);
    target->flags = mavlink_msg_target_get_flags(msg);
    target->package_endpoint_ip_1 = mavlink_msg_target_get_package_endpoint_ip_1(msg);
    target->package_endpoint_ip_2 = mavlink_msg_target_get_package_endpoint_ip_2(msg);
    target->package_endpoint_ip_3 = mavlink_msg_target_get_package_endpoint_ip_3(msg);
    target->confidence = mavlink_msg_target_get_confidence(msg);
    target->package_endpoint_port = mavlink_msg_target_get_package_endpoint_port(msg);
    target->prf_code = mavlink_msg_target_get_prf_code(msg);
    mavlink_msg_target_get_target_name(msg, target->target_name);
    target->target_class = mavlink_msg_target_get_target_class(msg);
    target->target_domain = mavlink_msg_target_get_target_domain(msg);
    target->target_entity_2525d = mavlink_msg_target_get_target_entity_2525d(msg);
    target->target_force = mavlink_msg_target_get_target_force(msg);
    target->sensor_type = mavlink_msg_target_get_sensor_type(msg);
    target->package_transport = mavlink_msg_target_get_package_transport(msg);
    mavlink_msg_target_get_package_path(msg, target->package_path);
    target->tle_category = mavlink_msg_target_get_tle_category(msg);
    target->dmpi_reference_kind = mavlink_msg_target_get_dmpi_reference_kind(msg);
    target->restricted_target_flags = mavlink_msg_target_get_restricted_target_flags(msg);
#else
        uint8_t len = msg->len < MAVLINK_MSG_ID_TARGET_LEN? msg->len : MAVLINK_MSG_ID_TARGET_LEN;
        memset(target, 0, MAVLINK_MSG_ID_TARGET_LEN);
    memcpy(target, _MAV_PAYLOAD(msg), len);
#endif

}
